<div class="row g-3">
<div class="col-md-4"><label class="form-label">Método</label><select class="form-select" name="method" required>@foreach(\App\Models\Shipment::METHODS as $value=>$label)<option value="{{ $value }}" @selected(old('method',$shipment->method)===$value)>{{ $label }}</option>@endforeach</select></div>
<div class="col-md-4"><label class="form-label">Paquetería / repartidor</label><input class="form-control" name="carrier" value="{{ old('carrier',$shipment->carrier) }}"></div>
<div class="col-md-4"><label class="form-label">Cobro contra entrega</label><input class="form-control" type="number" step=".01" min="0" name="cod_amount" value="{{ old('cod_amount',$shipment->cod_amount) }}"></div>
<div class="col-12"><hr><h2 class="h5">Destino</h2></div>
<div class="col-md-3"><label class="form-label">Código postal</label><div class="input-group"><input class="form-control" id="shipping-postal-code" name="destination_postal_code" maxlength="5" value="{{ old('destination_postal_code',$shipment->destination_postal_code) }}"><button class="btn btn-outline-dark" id="lookup-postal-code" type="button" title="Buscar dirección"><i class="bi bi-search"></i></button></div></div>
<div class="col-md-3"><label class="form-label">Estado</label><input class="form-control" id="shipping-state" name="destination_state" value="{{ old('destination_state',$shipment->destination_state) }}"></div>
<div class="col-md-3"><label class="form-label">Ciudad / alcaldía</label><input class="form-control" id="shipping-city" name="destination_city" value="{{ old('destination_city',$shipment->destination_city) }}"></div>
<div class="col-md-3"><label class="form-label">Colonia</label><select class="form-select" id="shipping-neighborhood" name="destination_neighborhood"><option value="{{ old('destination_neighborhood',$shipment->destination_neighborhood) }}">{{ old('destination_neighborhood',$shipment->destination_neighborhood) ?: 'Captura el CP' }}</option></select></div>
<div class="col-12"><label class="form-label">Dirección completa</label><textarea class="form-control" name="destination_address" rows="2">{{ old('destination_address',$shipment->destination_address ?: $shipment->order?->customer?->address) }}</textarea></div>
<div class="col-12"><hr><h2 class="h5">Paquete <small class="text-secondary">(kg y cm)</small></h2></div>
@foreach(['parcel_weight'=>'Peso','parcel_length'=>'Largo','parcel_width'=>'Ancho','parcel_height'=>'Alto'] as $name=>$label)<div class="col-6 col-md-3"><label class="form-label">{{ $label }}</label><input class="form-control" type="number" step="{{ $name==='parcel_weight'?'.01':'1' }}" min=".01" name="{{ $name }}" value="{{ old($name,$shipment->{$name}) }}"></div>@endforeach
@if($shipment->exists)<div class="col-12"><hr><h2 class="h5">Guía y servicio</h2></div><div class="col-md-4"><label class="form-label">Número de guía</label><input class="form-control" name="tracking_number" value="{{ old('tracking_number',$shipment->tracking_number) }}"></div><div class="col-md-4"><label class="form-label">URL de rastreo</label><input class="form-control" type="url" name="tracking_url" value="{{ old('tracking_url',$shipment->tracking_url) }}"></div><div class="col-md-2"><label class="form-label">Servicio cotizado</label><input class="form-control" name="quoted_service" value="{{ old('quoted_service',$shipment->quoted_service) }}"></div><div class="col-md-2"><label class="form-label">Costo cotizado</label><input class="form-control" type="number" step=".01" name="quoted_amount" value="{{ old('quoted_amount',$shipment->quoted_amount) }}"></div>@endif
</div>
