@extends('layouts.app')
@section('title','Centro de envios Skydropx | ForjaLab')
@section('content')
@php($tab=request('tab','quote'))
<section class="admin-section"><div class="container">
<div class="admin-header"><div><div class="eyebrow">Conexion directa</div><h1>Centro de envios Skydropx</h1><p class="text-secondary mb-0">Cotizaciones, guias, rastreo y recolecciones en un solo lugar.</p></div><div class="d-flex gap-2 align-items-center flex-wrap">@if($balance)<div class="sky-balance"><small>Credito disponible</small><strong>${{ number_format($balance['amount'],2) }} {{ $balance['currency'] }}</strong></div>@endif<a class="btn btn-outline-dark" href="{{ route('admin.shipments.index') }}">Envios internos</a></div></div>
@if($apiError)<div class="alert alert-warning"><i class="bi bi-cloud-slash me-2"></i>{{ $apiError }}</div>@endif
<ul class="nav nav-pills sky-tabs mb-4"><li><button class="nav-link {{ $tab==='quote'?'active':'' }}" data-bs-toggle="pill" data-bs-target="#quote"><i class="bi bi-calculator me-2"></i>Cotizador</button></li><li><button class="nav-link {{ $tab==='guides'?'active':'' }}" data-bs-toggle="pill" data-bs-target="#guides"><i class="bi bi-file-earmark-pdf me-2"></i>Guias <span class="badge text-bg-light">{{ $guides->count() }}</span></button></li><li><button class="nav-link {{ $tab==='pickups'?'active':'' }}" data-bs-toggle="pill" data-bs-target="#pickups"><i class="bi bi-box-arrow-in-up me-2"></i>Recolecciones <span class="badge text-bg-light">{{ $pickups->count() }}</span></button></li></ul>
<div class="tab-content">
<div class="tab-pane fade {{ $tab==='quote'?'show active':'' }}" id="quote"><div class="row g-4"><div class="col-lg-5"><form class="panel-card" id="quick-shipping-form">@csrf
<h2 class="h5 fw-bold">Destino</h2><small class="text-secondary">Origen ForjaLab, CP {{ config('services.skydropx.origin_postal_code') }}</small>
<div class="row g-3 mt-1"><div class="col-12"><label class="form-label">Codigo postal</label><div class="input-group"><input class="form-control" id="quick-postal" name="destination_postal_code" maxlength="5" required><button class="btn btn-outline-dark" id="quick-postal-search" type="button">Buscar</button></div></div><div class="col-6"><label class="form-label">Estado</label><input class="form-control" id="quick-state" name="destination_state" required></div><div class="col-6"><label class="form-label">Ciudad</label><input class="form-control" id="quick-city" name="destination_city" required></div><div class="col-12"><label class="form-label">Colonia</label><select class="form-select" id="quick-neighborhood" name="destination_neighborhood" required><option value="">Consulta el CP</option></select></div><div class="col-12"><hr><strong>Paquete (kg y cm)</strong></div>@foreach(['parcel_weight'=>'Peso','parcel_length'=>'Largo','parcel_width'=>'Ancho','parcel_height'=>'Alto'] as $field=>$label)<div class="col-6"><label class="form-label">{{ $label }}</label><input class="form-control" type="number" name="{{ $field }}" min=".01" step=".01" value="{{ $field==='parcel_weight'?1:30 }}" required></div>@endforeach</div>
<button class="btn btn-dark btn-lg w-100 mt-4" id="quick-quote-button">Consultar tarifas</button><div class="alert d-none mt-3 mb-0" id="quick-message"></div></form></div><div class="col-lg-7"><div class="panel-card quick-quote-results"><div id="quick-empty" class="text-center py-5"><i class="bi bi-box-seam display-4 text-secondary"></i><h2 class="h4 mt-3">Aqui apareceran las tarifas</h2></div><div id="quick-results"></div></div></div></div></div>
<div class="tab-pane fade {{ $tab==='guides'?'show active':'' }}" id="guides"><div class="panel-card"><div class="d-flex justify-content-between mb-3"><div><div class="eyebrow">Sincronizadas</div><h2 class="h4">Guias activas</h2></div><a class="btn btn-sm btn-outline-dark align-self-center" href="{{ route('admin.shipments.quick-quote',['tab'=>'guides']) }}"><i class="bi bi-arrow-clockwise"></i> Actualizar</a></div><div class="guide-list">
@forelse($guides as $guide) @php($share='Hola, rastrea tu envio ForjaLab'.($guide['tracking_number']?' con la guia '.$guide['tracking_number']:'').($guide['tracking_url']?' aqui: '.$guide['tracking_url']:''))
<article class="guide-card"><i class="bi bi-box-seam-fill"></i><div><strong>{{ $guide['carrier'] }}</strong><span>{{ $guide['recipient'] ?: 'Destinatario no disponible' }}</span><small>{{ $guide['tracking_number'] ?: 'Generando numero de rastreo' }} · {{ ucfirst(str_replace('_',' ',$guide['status'])) }}</small></div><div class="guide-actions">@if($guide['label_url'])<a class="btn btn-sm btn-dark" href="{{ $guide['label_url'] }}" target="_blank" rel="noopener"><i class="bi bi-file-earmark-pdf"></i> PDF</a>@endif @if($guide['tracking_url'])<a class="btn btn-sm btn-outline-dark" href="{{ $guide['tracking_url'] }}" target="_blank" rel="noopener">Rastrear</a>@endif @if($guide['tracking_number'])<a class="btn btn-sm btn-success" href="https://wa.me/?text={{ urlencode($share) }}" target="_blank" rel="noopener"><i class="bi bi-whatsapp"></i> Compartir</a>@endif</div></article>
@empty <p class="text-center text-secondary py-5">No hay guias activas en Skydropx.</p>@endforelse</div></div></div>
<div class="tab-pane fade {{ $tab==='pickups'?'show active':'' }}" id="pickups"><div class="row g-4"><div class="col-lg-5"><form class="panel-card" method="POST" action="{{ route('admin.shipments.pickups.store') }}" id="pickup-form">@csrf<div class="eyebrow">Nueva solicitud</div><h2 class="h4 mt-2">Pedir recoleccion</h2><label class="form-label">Guia</label><select class="form-select mb-2" name="reference_shipment_id" id="pickup-shipment" required><option value="">Selecciona</option>@foreach($guides as $guide)<option value="{{ $guide['id'] }}">{{ $guide['carrier'] }} · {{ $guide['tracking_number'] ?: Str::limit($guide['id'],12) }}</option>@endforeach</select><button class="btn btn-sm btn-outline-dark mb-3" type="button" id="pickup-coverage">Consultar cobertura</button><div class="alert d-none small" id="pickup-coverage-result"></div><div class="row g-3"><div class="col-6"><label class="form-label">Paquetes</label><input class="form-control" type="number" name="packages" min="1" value="1" required></div><div class="col-6"><label class="form-label">Peso total kg</label><input class="form-control" type="number" name="total_weight" min=".01" step=".01" value="1" required></div><div class="col-12"><label class="form-label">Desde</label><input class="form-control" type="datetime-local" name="scheduled_from" required></div><div class="col-12"><label class="form-label">Hasta</label><input class="form-control" type="datetime-local" name="scheduled_to" required></div></div><button class="btn btn-danger w-100 mt-4" @disabled($guides->isEmpty())>Solicitar a Skydropx</button></form></div><div class="col-lg-7"><div class="panel-card"><h2 class="h4">Recolecciones recientes</h2><div class="pickup-list">@forelse($pickups as $pickup)<article><span class="badge text-bg-{{ $pickup['error']?'danger':(in_array($pickup['status'],['scheduled','completed'])?'success':'warning') }}">{{ $pickup['status'] }}</span><div><strong>{{ $pickup['request_number'] ?: Str::limit($pickup['id'],12) }}</strong><small>{{ $pickup['packages'] }} paquete(s) · {{ $pickup['weight'] }} kg</small>@if($pickup['from'])<small>{{ \Illuminate\Support\Carbon::parse($pickup['from'])->format('d/m/Y H:i') }} - {{ \Illuminate\Support\Carbon::parse($pickup['to'])->format('H:i') }}</small>@endif @if($pickup['error'])<small class="text-danger">{{ $pickup['error'] }}</small>@endif</div></article>@empty<p class="text-secondary">No hay recolecciones registradas.</p>@endforelse</div></div></div></div></div>
</div></div></section>
<style>.sky-balance{display:grid;padding:.55rem .9rem;background:#e9f8ef;border:1px solid #b8e3c8;border-radius:.8rem}.sky-balance small{font-size:.67rem;color:#34714b}.sky-balance strong{color:#175b30}.sky-tabs{gap:.5rem;padding:.45rem;background:#ffffff99;border:1px solid var(--line);border-radius:1rem}.sky-tabs .nav-link{color:var(--ink);font-weight:800}.sky-tabs .active{background:linear-gradient(135deg,var(--forge-brown),var(--forge-orange))!important}.guide-list,.pickup-list{display:grid;gap:.75rem}.guide-card{display:grid;grid-template-columns:42px 1fr auto;align-items:center;gap:1rem;padding:1rem;border:1px solid var(--line);border-radius:.85rem}.guide-card>i{font-size:1.5rem;color:var(--forge-orange)}.guide-card strong,.guide-card span,.guide-card small,.pickup-list strong,.pickup-list small{display:block}.guide-card span,.guide-card small,.pickup-list small{color:var(--muted)}.guide-actions{display:flex;gap:.4rem;flex-wrap:wrap}.pickup-list article{display:flex;gap:.75rem;padding:.85rem;border:1px solid var(--line);border-radius:.8rem}@media(max-width:767px){.sky-tabs{flex-wrap:nowrap;overflow:auto}.sky-tabs button{white-space:nowrap}.guide-card{grid-template-columns:35px 1fr}.guide-actions{grid-column:1/-1}}</style>
@endsection
@push('scripts')
<script>document.addEventListener('DOMContentLoaded',()=>{const form=document.querySelector('#quick-shipping-form'),cp=document.querySelector('#quick-postal'),msg=document.querySelector('#quick-message'),results=document.querySelector('#quick-results'),empty=document.querySelector('#quick-empty'),button=document.querySelector('#quick-quote-button'),say=(t,k='danger')=>{msg.className=`alert alert-${k} mt-3 mb-0`;msg.textContent=t};document.querySelector('#quick-postal-search')?.addEventListener('click',async()=>{if(!/^\d{5}$/.test(cp.value))return say('Escribe un CP valido.');try{const r=await fetch(`{{ url('/admin/shipments/postal-code') }}/${cp.value}`,{headers:{Accept:'application/json'}}),j=await r.json();if(!r.ok)throw Error(j.message);document.querySelector('#quick-state').value=j.places[0].state;document.querySelector('#quick-city').value=j.places[0].city;document.querySelector('#quick-neighborhood').innerHTML=j.places.map(p=>`<option>${p.neighborhood}</option>`).join('');say('Ubicacion encontrada.','success')}catch(e){say(e.message)}});form?.addEventListener('submit',async e=>{e.preventDefault();button.disabled=true;say('Consultando Skydropx...','info');try{const r=await fetch(@json(route('admin.shipments.quick-quote.calculate')),{method:'POST',body:new FormData(form),headers:{Accept:'application/json'}}),j=await r.json();if(!r.ok)throw Error(j.message||Object.values(j.errors||{})[0]?.[0]);empty.hidden=true;results.innerHTML=`<h2 class="h4">${j.rates.length} tarifas</h2><div class="shipping-rates">${j.rates.map(x=>`<article class="shipping-rate"><i class="bi bi-truck"></i><span><strong>${x.carrier}</strong><small>${x.service} · ${x.days||'?'} dias</small></span><b>$${Number(x.price).toFixed(2)}</b></article>`).join('')}</div>`;say('Cotizacion lista.','success')}catch(e){say(e.message)}finally{button.disabled=false}});const cov=document.querySelector('#pickup-coverage'),sel=document.querySelector('#pickup-shipment'),out=document.querySelector('#pickup-coverage-result');cov?.addEventListener('click',async()=>{if(!sel.value)return;cov.disabled=true;try{const u=new URL(@json(route('admin.shipments.pickup-coverage')),location.origin);u.searchParams.set('shipment_id',sel.value);const r=await fetch(u,{headers:{Accept:'application/json'}}),j=await r.json();if(!r.ok)throw Error(j.message);out.className='alert alert-success small';out.textContent='Esta guia tiene cobertura. Selecciona una fecha valida de recoleccion.'}catch(e){out.className='alert alert-danger small';out.textContent=e.message}finally{cov.disabled=false}});document.querySelector('#pickup-form')?.addEventListener('submit',e=>{if(!confirm('¿Enviar esta solicitud de recoleccion a Skydropx?'))e.preventDefault()})});</script>
@endpush
