@extends('layouts.app')
@section('title','Cotizador de envíos | ForjaLab')
@section('content')
<section class="admin-section"><div class="container">
<div class="admin-header"><div><div class="eyebrow">Herramienta rápida</div><h1>Cotizador de envíos</h1><p class="text-secondary mb-0">Compara costos de Skydropx sin crear un pedido ni generar una guía.</p></div><a class="btn btn-outline-dark" href="{{ route('admin.shipments.index') }}"><i class="bi bi-truck me-2"></i>Ver envíos</a></div>
<div class="row g-4"><div class="col-lg-5"><form class="panel-card" id="quick-shipping-form">@csrf
<div class="d-flex align-items-center gap-3 mb-4"><span class="feature-icon mb-0"><i class="bi bi-geo-alt-fill"></i></span><div><h2 class="h5 fw-bold mb-1">Destino</h2><small class="text-secondary">El origen es el taller ForjaLab, CP {{ config('services.skydropx.origin_postal_code') }}.</small></div></div>
<div class="row g-3"><div class="col-12"><label class="form-label">Código postal destino</label><div class="input-group"><input class="form-control form-control-lg" id="quick-postal" name="destination_postal_code" inputmode="numeric" maxlength="5" placeholder="Ej. 06600" required><button class="btn btn-outline-dark" id="quick-postal-search" type="button"><i class="bi bi-search me-1"></i>Buscar</button></div></div>
<div class="col-md-6"><label class="form-label">Estado</label><input class="form-control" id="quick-state" name="destination_state" required></div><div class="col-md-6"><label class="form-label">Ciudad / municipio</label><input class="form-control" id="quick-city" name="destination_city" required></div><div class="col-12"><label class="form-label">Colonia</label><select class="form-select" id="quick-neighborhood" name="destination_neighborhood" required><option value="">Primero consulta el CP</option></select></div>
<div class="col-12"><hr><h2 class="h5 fw-bold">Paquete <small class="text-secondary">kg y cm</small></h2></div><div class="col-6"><label class="form-label">Peso</label><input class="form-control" type="number" name="parcel_weight" step=".01" min=".01" value="1" required></div><div class="col-6"><label class="form-label">Largo</label><input class="form-control" type="number" name="parcel_length" min="1" value="30" required></div><div class="col-6"><label class="form-label">Ancho</label><input class="form-control" type="number" name="parcel_width" min="1" value="30" required></div><div class="col-6"><label class="form-label">Alto</label><input class="form-control" type="number" name="parcel_height" min="1" value="30" required></div></div>
<button class="btn btn-dark btn-lg w-100 mt-4" id="quick-quote-button"><i class="bi bi-calculator me-2"></i>Consultar tarifas</button><div class="alert d-none mt-3 mb-0" id="quick-message"></div></form></div>
<div class="col-lg-7"><div class="panel-card quick-quote-results"><div id="quick-empty" class="text-center py-5"><i class="bi bi-box-seam display-4 text-secondary"></i><h2 class="h4 mt-3">Aquí aparecerán las tarifas</h2><p class="text-secondary">Completa el destino y las medidas para comparar paqueterías.</p></div><div id="quick-results"></div></div></div></div>
</div></section>
@endsection
@push('scripts')
<script>
document.addEventListener('DOMContentLoaded',()=>{const form=document.querySelector('#quick-shipping-form'),cp=document.querySelector('#quick-postal'),msg=document.querySelector('#quick-message'),results=document.querySelector('#quick-results'),empty=document.querySelector('#quick-empty'),button=document.querySelector('#quick-quote-button');const message=(text,type='danger')=>{msg.className=`alert alert-${type} mt-3 mb-0`;msg.textContent=text};
document.querySelector('#quick-postal-search').addEventListener('click',async()=>{if(!/^\d{5}$/.test(cp.value))return message('Escribe un código postal válido de 5 dígitos.');message('Buscando ubicación…','info');try{const r=await fetch(`{{ url('/admin/shipments/postal-code') }}/${cp.value}`,{headers:{Accept:'application/json'}}),j=await r.json();if(!r.ok)throw new Error(j.message);if(!j.places?.length)throw new Error('No encontramos ubicaciones para ese CP.');document.querySelector('#quick-state').value=j.places[0].state;document.querySelector('#quick-city').value=j.places[0].city;document.querySelector('#quick-neighborhood').innerHTML=j.places.map(p=>`<option>${p.neighborhood}</option>`).join('');message(`${j.places.length} colonia(s) encontradas.`,'success')}catch(e){message(e.message)}});
form.addEventListener('submit',async e=>{e.preventDefault();button.disabled=true;button.innerHTML='<span class="spinner-border spinner-border-sm me-2"></span>Consultando Skydropx';message('Esperando precios finales de las paqueterías…','info');results.innerHTML='';try{const r=await fetch(`{{ route('admin.shipments.quick-quote.calculate') }}`,{method:'POST',body:new FormData(form),headers:{Accept:'application/json'}}),j=await r.json();if(!r.ok)throw new Error(j.message||Object.values(j.errors||{})[0]?.[0]);if(!j.rates?.length)throw new Error('Skydropx no devolvió tarifas disponibles para este paquete y destino.');empty.hidden=true;results.innerHTML=`<div class="d-flex justify-content-between align-items-center mb-3"><div><div class="eyebrow">Resultados</div><h2 class="h4 mb-0">${j.rates.length} tarifas disponibles</h2></div><small>${j.quoted_at}</small></div><div class="shipping-rates">${j.rates.map(x=>`<article class="shipping-rate"><i class="bi bi-truck fs-4"></i><span><strong>${x.carrier}</strong><small>${x.service} · ${x.days?x.days+' días':'Entrega por confirmar'}</small></span><b>$${Number(x.price).toLocaleString('es-MX',{minimumFractionDigits:2})}</b></article>`).join('')}</div><p class="text-secondary small mt-3 mb-0"><i class="bi bi-info-circle me-1"></i>Precios informativos sujetos a vigencia y disponibilidad de Skydropx.</p>`;message('Cotización completada.','success')}catch(e){empty.hidden=false;message(e.message)}finally{button.disabled=false;button.innerHTML='<i class="bi bi-calculator me-2"></i>Consultar tarifas'}});
});
</script>
@endpush
