@extends('layouts.app')

@php
    $isEdit = $campaign->exists;
    $featuredValue = $campaign->featured_type && $campaign->featured_id ? $campaign->featured_type.':'.$campaign->featured_id : '';
    $relatedIds = old('related_product_ids', $campaign->related_product_ids ?? []);
    $nameVariable = chr(123).chr(123).'nombre'.chr(125).chr(125);
    $defaultContent = '<h1>Tenemos algo especial para ti</h1><p>Hola '.$nameVariable.', conoce las novedades que preparamos en ForjaLab.</p>';
@endphp
@section('title', ($isEdit ? 'Editar campaña' : 'Nueva campaña').' | ForjaLab')

@section('content')
<section class="admin-section"><div class="container">
    @include('admin.partials.menu')
    <div class="admin-header"><div><div class="eyebrow">Email builder</div><h1 class="fw-bold mt-2 mb-0">{{ $isEdit ? $campaign->name : 'Nueva campaña' }}</h1></div><div class="d-flex flex-wrap gap-2"><a class="btn btn-outline-dark" href="{{ route('admin.mailing.index') }}"><i class="bi bi-arrow-left me-2"></i>Volver</a>@if($isEdit)<a class="btn btn-outline-dark" href="{{ route('admin.mailing.preview',$campaign) }}" target="_blank"><i class="bi bi-eye me-2"></i>Vista previa</a>@endif</div></div>

    <form method="POST" action="{{ $isEdit ? route('admin.mailing.update',$campaign) : route('admin.mailing.store') }}" enctype="multipart/form-data">@csrf @if($isEdit)@method('PUT')@endif
        <div class="mailing-builder-grid">
            <div>
                <div class="panel-card mb-4"><div class="form-section-title"><i class="bi bi-envelope-heart-fill"></i><div><h2>Información de la campaña</h2><p>Nombre interno y texto que verá el destinatario.</p></div></div><div class="row g-3"><div class="col-md-6"><label class="form-label">Nombre interno</label><input class="form-control" name="name" value="{{ old('name',$campaign->name) }}" required></div><div class="col-md-6"><label class="form-label">Asunto del correo</label><input class="form-control" name="subject" value="{{ old('subject',$campaign->subject) }}" required></div><div class="col-12"><label class="form-label">Texto previo</label><input class="form-control" name="preview_text" value="{{ old('preview_text',$campaign->preview_text) }}" placeholder="Se muestra junto al asunto en algunas bandejas"></div></div></div>

                <div class="panel-card mb-4"><div class="form-section-title"><i class="bi bi-magic"></i><div><h2>Contenido</h2><p>Usa <code>{{ $nameVariable }}</code> para personalizar el saludo.</p></div></div><textarea id="campaignEditor" name="content_html">{{ old('content_html',$campaign->content_html ?: $defaultContent) }}</textarea></div>

                <div class="panel-card mb-4"><div class="form-section-title"><i class="bi bi-bag-heart-fill"></i><div><h2>Productos del correo</h2><p>Selecciona los productos y carga una plantilla que podrás modificar libremente.</p></div></div><label class="form-label">Producto o paquete destacado</label><select class="form-select mb-3" name="featured_item" data-mailing-featured><option value="">Sin producto destacado</option><optgroup label="Productos">@foreach($products as $product)<option value="product:{{ $product->id }}" @selected(old('featured_item',$featuredValue)==='product:'.$product->id)>{{ $product->name }} · ${{ number_format((float)$product->public_price,0) }}</option>@endforeach</optgroup><optgroup label="Paquetes">@foreach($bundles as $bundle)<option value="bundle:{{ $bundle->id }}" @selected(old('featured_item',$featuredValue)==='bundle:'.$bundle->id)>{{ $bundle->name }} · ${{ number_format((float)$bundle->public_price,0) }}</option>@endforeach</optgroup></select><label class="form-label">Productos relacionados <small class="text-secondary">(máximo 6)</small></label><div class="mailing-product-options">@foreach($products as $product)<label><input type="checkbox" name="related_product_ids[]" value="{{ $product->id }}" data-mailing-related @checked(in_array($product->id,$relatedIds))>@if($product->image_url)<img src="{{ $product->image_url }}" alt="">@else<i class="bi bi-box-seam"></i>@endif<span>{{ $product->name }}<small>${{ number_format((float)$product->public_price,0) }}</small></span></label>@endforeach</div><button class="btn btn-warning w-100 mt-3" type="button" data-load-mailing-template><i class="bi bi-magic me-2"></i>Cargar plantilla y preview en el editor</button><div class="form-text">La plantilla se podrá editar completamente dentro de TinyMCE.</div></div>
            </div>

            <aside><div class="panel-card mailing-recipient-panel"><div class="form-section-title"><i class="bi bi-people-fill"></i><div><h2>Destinatarios</h2><p>Selecciona clientes o carga una lista.</p></div></div>@if($isEdit && $campaign->recipients->isNotEmpty())<div class="alert alert-light"><strong>{{ $campaign->recipients->count() }} destinatarios guardados</strong><small class="d-block">Sólo agrega otra lista si deseas reemplazarlos.</small></div>@endif<label class="form-label">Clientes registrados</label><div class="mailing-customer-list">@forelse($customers as $customer)<label><input type="checkbox" name="customer_ids[]" value="{{ $customer->id }}"><span>{{ $customer->name }}<small>{{ $customer->email }}</small></span></label>@empty<small class="text-secondary">No hay clientes con correo.</small>@endforelse</div><label class="form-label mt-3">Pegar destinatarios</label><textarea class="form-control" name="recipient_text" rows="6" placeholder="correo@ejemplo.com&#10;Nombre,correo@ejemplo.com">{{ old('recipient_text') }}</textarea><div class="form-text">Un correo por línea o formato Nombre,correo. Se eliminan duplicados.</div><label class="form-label mt-3">Archivo CSV o TXT</label><input class="form-control" type="file" name="recipient_file" accept=".csv,.txt"><div class="alert alert-warning mt-3 mb-0"><i class="bi bi-shield-check me-2"></i>Máximo 200 destinatarios por mini campaña.</div></div></aside>
        </div>
        <div class="d-flex flex-wrap gap-2 mt-4"><button class="btn btn-dark btn-lg" type="submit"><i class="bi bi-save me-2"></i>{{ $isEdit ? 'Guardar cambios' : 'Crear campaña' }}</button></div>
    </form>
    @if($isEdit)<div class="panel-card mailing-send-panel mt-4"><div><div class="eyebrow">Último paso</div><h2>Revisa la vista previa antes de enviar</h2><p>El envío registra cada destinatario y permite consultar aperturas y clics.</p></div><div class="mailing-send-actions"><form method="POST" action="{{ route('admin.mailing.send',$campaign) }}" onsubmit="return confirm('¿Enviar esta campaña a {{ $campaign->recipient_count }} destinatarios?')">@csrf<button class="btn btn-success btn-lg" type="submit" @disabled(!$campaign->recipient_count || $campaign->status === 'sent')><i class="bi bi-send-fill me-2"></i>Enviar campaña</button></form>@if(in_array($campaign->status,['sent','partial']))<form method="POST" action="{{ route('admin.mailing.resend',$campaign) }}" onsubmit="return confirm('¿Reenviar la campaña a todos los destinatarios? Las métricas actuales de aperturas y clics se reiniciarán.')">@csrf<button class="btn btn-warning btn-lg" type="submit"><i class="bi bi-arrow-repeat me-2"></i>Reenviar campaña</button></form>@endif</div></div>@endif
    @if($isEdit && $campaign->recipients->isNotEmpty())
        @php
            $openedCount = $campaign->recipients->whereNotNull('opened_at')->count();
            $clickedCount = $campaign->recipients->whereNotNull('clicked_at')->count();
            $openRate = $campaign->sent_count ? round(($openedCount / $campaign->sent_count) * 100) : 0;
            $clickRate = $campaign->sent_count ? round(($clickedCount / $campaign->sent_count) * 100) : 0;
        @endphp
        <div class="panel-card mt-4"><div class="form-section-title"><i class="bi bi-bar-chart-fill"></i><div><h2>Analítica de la campaña</h2><p>Las aperturas son aproximadas; algunos proveedores precargan o bloquean imágenes.</p></div></div><div class="mailing-analytics-summary"><div><i class="bi bi-send-check-fill"></i><strong>{{ $campaign->sent_count }}</strong><span>Aceptados por SMTP</span></div><div><i class="bi bi-envelope-open-fill"></i><strong>{{ $openedCount }}</strong><span>Abrieron · {{ $openRate }}%</span></div><div><i class="bi bi-cursor-fill"></i><strong>{{ $clickedCount }}</strong><span>Hicieron clic · {{ $clickRate }}%</span></div><div><i class="bi bi-exclamation-triangle-fill"></i><strong>{{ $campaign->failed_count }}</strong><span>Con error</span></div></div>
        <div class="table-responsive mailing-analytics-table"><table class="table align-middle mb-0"><thead><tr><th>Destinatario</th><th>Envío</th><th>Aperturas</th><th>Clics</th><th>Último enlace</th></tr></thead><tbody>@foreach($campaign->recipients->sortByDesc(fn($item)=>$item->clicked_at ?: $item->opened_at ?: $item->sent_at) as $recipientRow)<tr><td><strong>{{ $recipientRow->name ?: 'Sin nombre' }}</strong><small class="d-block text-secondary">{{ $recipientRow->email }}</small></td><td><span class="badge text-bg-{{ $recipientRow->status === 'sent' ? 'success' : ($recipientRow->status === 'failed' ? 'danger' : 'secondary') }}">{{ $recipientRow->status === 'sent' ? 'Enviado' : ucfirst($recipientRow->status) }}</span><small class="d-block text-secondary mt-1">{{ $recipientRow->sent_at?->format('d/m/Y H:i') }}</small></td><td><strong>{{ $recipientRow->open_count }}</strong>@if($recipientRow->opened_at)<small class="d-block text-secondary">{{ $recipientRow->opened_at->format('d/m/Y H:i') }}</small>@endif</td><td><strong>{{ $recipientRow->click_count }}</strong>@if($recipientRow->clicked_at)<small class="d-block text-secondary">{{ $recipientRow->clicked_at->format('d/m/Y H:i') }}</small>@endif</td><td>@if($recipientRow->last_clicked_url)<a href="{{ $recipientRow->last_clicked_url }}" target="_blank" rel="noopener" title="{{ $recipientRow->last_clicked_url }}">{{ \Illuminate\Support\Str::limit(parse_url($recipientRow->last_clicked_url,PHP_URL_HOST).parse_url($recipientRow->last_clicked_url,PHP_URL_PATH),34) }}</a>@else<span class="text-secondary">—</span>@endif</td></tr>@endforeach</tbody></table></div></div>
    @endif
</div></section>

<script src="https://cdn.jsdelivr.net/npm/tinymce@7/tinymce.min.js" referrerpolicy="origin"></script>
<script type="application/json" id="mailingCatalogData">{!! json_encode([
    'product' => $products->mapWithKeys(fn($item) => [$item->id => ['name'=>$item->name,'description'=>$item->description,'price'=>(float)$item->public_price,'image'=>$item->image_url,'gallery'=>collect([$item->image_url])->merge($item->photos->map->image_url)->filter()->unique()->values()->all(),'kind'=>'producto']]),
    'bundle' => $bundles->mapWithKeys(fn($item) => [$item->id => ['name'=>$item->name,'description'=>$item->description,'price'=>(float)$item->public_price,'image'=>$item->image_url,'gallery'=>collect([$item->image_url])->merge($item->photos->map->image_url)->filter()->unique()->values()->all(),'kind'=>'paquete']])
], JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) !!}</script>
<script>
const mailingCatalog = JSON.parse(document.getElementById('mailingCatalogData').textContent);
const mailingMoney = value => new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0}).format(value || 0);
const mailingSafe = value => String(value || '').replace(/[&<>'"]/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[char]));
const mailingWhatsapp = item => `https://wa.me/525564442949?text=${encodeURIComponent(`Hola, vi el ${item.kind || 'producto'} ${item.name} en un correo de ForjaLab y quiero recibir más información.`)}`;
const mailingGallery = item => (item.gallery || []).slice(1,5).length ? `<table role="presentation" cellspacing="5" cellpadding="0" style="width:100%;margin-top:7px"><tbody><tr>${item.gallery.slice(1,5).map(image => `<td style="width:25%"><img src="${mailingSafe(image)}" alt="${mailingSafe(item.name)}" style="display:block;width:100%;height:64px;object-fit:cover;background:#f2eee9"></td>`).join('')}</tr></tbody></table>` : '';
const mailingFeaturedProduct = item => `<table class="fl-featured" data-forjalab-product="1" role="presentation" cellspacing="0" cellpadding="0" style="width:100%;margin:30px auto 42px;background:#fff"><tbody><tr>${item.image ? `<td class="fl-featured-media" style="width:52%;vertical-align:middle"><img src="${mailingSafe(item.image)}" alt="${mailingSafe(item.name)}" style="display:block;width:100%;height:300px;object-fit:cover;background:#f5f2ee">${mailingGallery(item)}</td>` : ''}<td class="fl-featured-copy" style="width:48%;padding:25px 10px 25px 34px;vertical-align:middle"><small style="color:#897b70;font-size:11px;letter-spacing:1.5px;text-transform:uppercase">Selección ForjaLab</small><h2 style="margin:10px 0 12px;color:#241811;font-size:28px;line-height:1.08">${mailingSafe(item.name)}</h2><p style="margin:0 0 14px;color:#6f655e;font-size:14px;line-height:1.55">${mailingSafe(item.description)}</p>${item.price ? `<strong style="display:block;margin:0 0 18px;color:#241811;font-size:22px">${mailingMoney(item.price)}</strong>` : ''}<a class="fl-product-button" href="${mailingWhatsapp(item)}" style="display:inline-block;padding:11px 18px;color:#fff;background:#25d366;text-decoration:none;font-size:12px;font-weight:bold;border-radius:99px">Información del producto</a></td></tr></tbody></table>`;
const mailingRelatedCell = item => `<td class="fl-related-cell" style="width:33.33%;padding:0 6px;vertical-align:top"><table role="presentation" cellspacing="0" cellpadding="0" style="width:100%;background:#372116"><tbody><tr>${item.image ? `<td class="fl-related-image" style="width:43%;padding:8px"><img src="${mailingSafe(item.image)}" alt="${mailingSafe(item.name)}" style="display:block;width:100%;height:92px;object-fit:cover;background:#eee"></td>` : ''}<td class="fl-related-copy" style="padding:10px 8px 10px 3px;vertical-align:middle"><strong style="display:block;color:#fff;font-size:12px;line-height:1.2">${mailingSafe(item.name)}</strong>${item.price ? `<small style="display:block;margin:5px 0;color:#d8c9be;font-size:10px">${mailingMoney(item.price)}</small>` : ''}<a href="${mailingWhatsapp(item)}" style="color:#7ee3a1;font-size:10px;font-weight:bold;text-decoration:none">Información →</a></td></tr></tbody></table></td>`;
const mailingRelatedGrid = items => `<table class="fl-related-grid" data-forjalab-product="1" role="presentation" cellspacing="0" cellpadding="0" style="width:100%;margin:15px 0 25px"><tbody>${Array.from({length:Math.ceil(items.length/3)},(_,row) => { const group=items.slice(row*3,row*3+3); return `<tr>${group.map(mailingRelatedCell).join('')}${'<td class="fl-related-cell fl-related-empty" style="width:33.33%"></td>'.repeat(3-group.length)}</tr><tr class="fl-related-spacer"><td colspan="3" style="height:12px"></td></tr>`; }).join('')}</tbody></table>`;
const mailingHeader = `<table class="fl-header" data-forjalab-header="1" role="presentation" cellspacing="0" cellpadding="0" style="width:100%;margin:0 0 32px;border-bottom:1px solid #e9e3dd"><tbody><tr><td class="fl-header-logo" style="width:70px;padding:16px 0"><img src="{{ asset('icon-192.png') }}" alt="ForjaLab" style="display:block;width:58px;height:58px;border-radius:50%"></td><td class="fl-header-brand" style="padding:16px 0"><strong style="display:block;color:#241811;font-size:22px">ForjaLab</strong><span style="color:#7c7068;font-size:12px">Personalización · Láser · Textil · QR y NFC</span></td><td class="fl-header-info" style="padding:16px 0;text-align:right"><a href="{{ route('home') }}" style="color:#372116;font-size:12px;font-weight:bold;text-decoration:none">forjalab.com.mx</a><br><span style="color:#8c8179;font-size:11px">Ciudad de México</span></td></tr></tbody></table>`;
const mailingFooter = `<table class="fl-footer" data-forjalab-footer="1" role="presentation" cellspacing="0" cellpadding="0" style="width:100%;margin:38px 0 0;background:#241811"><tbody><tr><td style="padding:28px 24px;text-align:center"><strong style="display:block;margin-bottom:7px;color:#fff;font-size:20px">¿Creamos algo juntos?</strong><span style="display:block;margin-bottom:18px;color:#cdbfb5;font-size:12px">Cuéntanos tu idea y recibe atención personalizada.</span><a class="fl-whatsapp-button" href="https://wa.me/525564442949?text=Hola%2C%20vi%20su%20correo%20y%20quiero%20una%20cotizaci%C3%B3n" style="display:inline-block;padding:12px 22px;color:#fff;background:#25d366;text-decoration:none;font-size:13px;font-weight:bold;border-radius:99px">Escribir por WhatsApp</a><div class="fl-socials" style="margin-top:20px"><a href="https://www.facebook.com/people/ForjaLab/61593399118406/" style="margin:0 8px;color:#fff;font-size:11px;text-decoration:none">Facebook</a><a href="https://www.instagram.com/forjalabby/" style="margin:0 8px;color:#fff;font-size:11px;text-decoration:none">Instagram</a><a href="https://www.tiktok.com/@forjalab3" style="margin:0 8px;color:#fff;font-size:11px;text-decoration:none">TikTok</a></div><small style="display:block;margin-top:20px;color:#8f7f73;font-size:9px">Recibiste este correo porque compartiste tus datos con ForjaLab.</small></td></tr></tbody></table>`;
tinymce.init({selector:'#campaignEditor',license_key:'gpl',height:600,menubar:false,convert_urls:false,relative_urls:false,remove_script_host:false,document_base_url:'{{ url('/') }}/',plugins:'lists link image table code preview autoresize',toolbar:'undo redo | blocks | bold italic forecolor | alignleft aligncenter alignright | bullist numlist | link image table | code preview',extended_valid_elements:'table[*],tbody[*],tr[*],td[*],img[*],a[*],div[*],span[*],small[*],strong[*],h1[*],h2[*],p[*]',content_style:'body{max-width:640px;margin:0 auto;font-family:Arial,sans-serif;font-size:16px;color:#302218;line-height:1.6;padding:28px;background:#fff}'});
document.querySelector('[data-load-mailing-template]')?.addEventListener('click', () => {
    const editor = tinymce.get('campaignEditor');
    if (!editor) return;
    const current = editor.getContent({format:'text'}).trim();
    if (current && !confirm('Se reemplazará el contenido actual del editor. ¿Deseas continuar?')) return;
    const [type,id] = document.querySelector('[data-mailing-featured]').value.split(':');
    const featured = mailingCatalog[type]?.[id];
    const related = [...document.querySelectorAll('[data-mailing-related]:checked')].slice(0,6).map(input => mailingCatalog.product[input.value]).filter(Boolean);
    let html = mailingHeader + `<div style="padding:8px 0 4px;text-align:center"><small style="color:#8a7d74;font-size:11px;letter-spacing:2px;text-transform:uppercase">Novedades ForjaLab</small><h1 style="margin:9px 0 7px;color:#241811;font-size:32px;line-height:1.1">Una idea especial para ti</h1><p style="margin:0;color:#766b64;font-size:14px">Hola {{ $nameVariable }}, conoce nuestra selección de productos personalizados.</p></div>`;
    if (featured) html += mailingFeaturedProduct(featured);
    if (related.length) html += `<h2 style="margin:0 0 12px;color:#241811;font-size:19px;text-align:center">También te puede interesar</h2>` + mailingRelatedGrid(related);
    html += `<p style="margin:30px auto 5px;max-width:500px;color:#766b64;font-size:13px;text-align:center">¿Necesitas otra cantidad, diseño o personalización? Responde este correo y prepararemos tu cotización.</p>` + mailingFooter;
    editor.setContent(html);
    editor.focus();
    document.getElementById('campaignEditor').scrollIntoView({behavior:'smooth',block:'center'});
});
</script>
@endsection
