@extends('layouts.app')
@section('title','Capturar avance '.$shipment->order->folio.' | ForjaLab')
@section('content')
<section class="shipment-capture-page"><div class="container"><div class="shipment-capture-shell">
    <header><img src="{{ asset('icon-192.png') }}" alt="ForjaLab"><div><span class="eyebrow">Evidencia de pedido</span><h1>{{ $shipment->order->folio }}</h1><p>{{ $shipment->order->customer->name }}</p></div></header>
    @if(session('status'))<div class="capture-success"><i class="bi bi-check-circle-fill"></i><div><strong>¡Fotografías publicadas!</strong><p>{{ session('status') }}</p><a href="{{ $shipment->public_url }}" target="_blank">Ver seguimiento del cliente</a></div></div>@endif
    @if($errors->any())<div class="alert alert-danger"><strong>No pudimos subir las fotos.</strong><ul class="mb-0 mt-2">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <form method="POST" enctype="multipart/form-data" action="{{ route('shipments.capture.store', $shipment->capture_token) }}" data-capture-form>@csrf
        <div class="capture-field"><label><i class="bi bi-signpost-split-fill"></i> ¿En qué etapa está?</label><div class="capture-stages">@foreach($stages as $key => $stage)<label><input type="radio" name="stage" value="{{ $key }}" @checked(old('stage', $shipment->order->status === 'ready' ? 'ready' : ($shipment->order->status === 'delivered' ? 'delivered' : 'production')) === $key)><span><i class="bi bi-{{ $key === 'production' ? 'tools' : ($key === 'ready' ? 'box-seam-fill' : 'check-circle-fill') }}"></i>{{ $key === 'production' ? 'En producción' : ($key === 'ready' ? 'Listo' : 'Entregado') }}</span></label>@endforeach</div></div>
        <div class="capture-field"><label for="evidence"><i class="bi bi-camera-fill"></i> Toma o selecciona fotografías</label><label class="capture-camera" for="evidence"><i class="bi bi-camera-fill"></i><strong>Abrir cámara</strong><small>Puedes agregar hasta 6 fotos</small></label><input class="visually-hidden" id="evidence" type="file" name="evidence[]" accept="image/jpeg,image/png,image/webp" capture="environment" multiple required data-capture-input><div class="capture-preview" data-capture-preview></div></div>
        <div class="capture-field"><label for="capture-description"><i class="bi bi-chat-left-text-fill"></i> Nota opcional</label><textarea class="form-control" id="capture-description" name="description" rows="3" maxlength="1000" placeholder="Ej. Terminamos el grabado y estamos revisando los detalles.">{{ old('description') }}</textarea></div>
        <button class="btn btn-dark btn-lg w-100" type="submit" data-capture-submit><i class="bi bi-cloud-arrow-up-fill me-2"></i>Publicar avance</button><p class="capture-privacy"><i class="bi bi-shield-lock-fill"></i> Este enlace es privado. Las fotos serán visibles en el seguimiento del cliente.</p>
    </form>
</div></div></section>
<script>document.addEventListener('DOMContentLoaded',()=>{const input=document.querySelector('[data-capture-input]'),preview=document.querySelector('[data-capture-preview]'),form=document.querySelector('[data-capture-form]'),submit=document.querySelector('[data-capture-submit]');input?.addEventListener('change',()=>{preview.innerHTML='';[...input.files].slice(0,6).forEach(file=>{const img=document.createElement('img');img.src=URL.createObjectURL(file);img.alt='Foto seleccionada';preview.append(img)})});form?.addEventListener('submit',()=>{submit.disabled=true;submit.innerHTML='<span class="spinner-border spinner-border-sm me-2"></span>Publicando fotos…'})});</script>
@endsection
