@extends('layouts.app')
@section('title', 'Galería de Drive | ForjaLab')
@section('content')
<section class="admin-section"><div class="container">
    <div class="admin-header"><div><div class="eyebrow">Recursos compartidos</div><h1 class="fw-bold mt-2 mb-0">Galería de imágenes</h1><p class="text-secondary mt-2 mb-0">Consulta, descarga y carga archivos de Drive sin salir del sistema.</p></div><div class="d-flex gap-2 flex-wrap">@can('orders.manage')@if($oauthConfigured && !$driveConnected)<a class="btn btn-primary" href="{{ route('admin.drive-gallery.google.connect') }}"><i class="bi bi-google me-2"></i>Conectar Google Drive</a>@endif<button class="btn btn-success" type="button" data-bs-toggle="modal" data-bs-target="#driveUploadModal" @disabled(!$driveConnected)><i class="bi bi-cloud-arrow-up-fill me-2"></i>Cargar imágenes</button>@endcan<button class="btn btn-outline-dark" type="button" data-gallery-refresh><i class="bi bi-arrow-clockwise me-2"></i>Actualizar</button><a class="btn btn-dark" href="{{ $folderUrl }}" target="_blank" rel="noopener"><i class="bi bi-google me-2"></i>Abrir Drive</a></div></div>
    @can('orders.manage')
        @if(!$oauthConfigured)<div class="alert alert-warning"><i class="bi bi-key-fill me-2"></i>Faltan las credenciales OAuth o la URL de redirección de Google Drive. Revisa el archivo <code>.env</code> y limpia la caché.</div>
        @elseif(!$driveConnected)<div class="alert alert-info"><i class="bi bi-google me-2"></i>Conecta la cuenta propietaria de la carpeta para habilitar la carga de imágenes.</div>
        @else<div class="alert alert-success"><i class="bi bi-check-circle-fill me-2"></i>Google Drive está conectado. Las cargas se guardarán en la carpeta seleccionada.</div>@endif
    @endcan
    <div class="panel-card drive-native-gallery"><nav class="drive-breadcrumb d-none" aria-label="Carpetas" data-gallery-breadcrumb></nav><div class="drive-gallery-status" data-gallery-status><span class="spinner-border spinner-border-sm"></span>Cargando imágenes...</div><div class="drive-folder-grid" data-folder-grid></div><div class="drive-image-grid" data-gallery-grid></div></div>
</div></section>

<div class="modal fade" id="driveImageModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-xl modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h2 class="modal-title h5 fw-bold" data-preview-name>Imagen</h2><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button></div><div class="modal-body drive-preview-body"><img src="" alt="" data-preview-image></div><div class="modal-footer"><a class="btn btn-outline-dark" target="_blank" rel="noopener" data-preview-drive><i class="bi bi-box-arrow-up-right me-1"></i>Ver en Drive</a><a class="btn btn-dark" data-preview-download><i class="bi bi-download me-1"></i>Descargar</a></div></div></div></div>

@can('orders.manage')
<div class="modal fade" id="driveUploadModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><form data-upload-form><div class="modal-header"><div><div class="eyebrow">Google Drive</div><h2 class="modal-title h4 fw-bold">Cargar imágenes</h2></div><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button></div><div class="modal-body"><div class="row g-3"><div class="col-12"><label class="form-label"><i class="bi bi-folder-fill me-1 text-warning"></i>Carpeta de destino</label><select class="form-select" name="folder_id" required data-upload-folder></select></div><div class="col-12"><label class="form-label"><i class="bi bi-images me-1 text-success"></i>Imágenes</label><input class="form-control" type="file" name="images[]" accept="image/jpeg,image/png,image/webp,image/gif" multiple required><small class="text-secondary">Hasta 20 imágenes por carga y 20 MB por archivo.</small></div><div class="col-12 d-none" data-upload-progress-wrap><div class="d-flex justify-content-between mb-1"><small>Subiendo a Drive...</small><strong data-upload-percent>0%</strong></div><div class="progress" role="progressbar"><div class="progress-bar progress-bar-striped progress-bar-animated bg-success" style="width:0" data-upload-progress></div></div></div><div class="col-12"><div class="alert d-none mb-0" data-upload-message></div></div></div></div><div class="modal-footer"><button class="btn btn-outline-secondary" type="button" data-bs-dismiss="modal">Cancelar</button><button class="btn btn-success" type="submit" data-upload-submit><i class="bi bi-cloud-arrow-up-fill me-1"></i>Subir a Drive</button></div></form></div></div></div>
@endcan

<style>.drive-native-gallery{min-height:420px}.drive-gallery-status{display:flex;align-items:center;justify-content:center;gap:.65rem;min-height:320px;color:var(--muted);font-weight:800}.drive-gallery-status.is-error{color:#a52d20}.drive-breadcrumb{display:flex;align-items:center;gap:.4rem;margin-bottom:1.2rem;padding:.75rem 1rem;background:#fff8ed;border:1px solid var(--line);border-radius:.8rem}.drive-breadcrumb button{padding:0;color:var(--forge-brown);font-weight:800;background:none;border:0}.drive-breadcrumb i{color:var(--muted);font-size:.72rem}.drive-folder-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:.8rem;margin-bottom:1.2rem}.drive-folder-card{display:flex;align-items:center;gap:.8rem;padding:1rem;text-align:left;background:linear-gradient(135deg,#fff8e9,#fff);border:1px solid #ead8bc;border-radius:.9rem;transition:transform .2s,box-shadow .2s}.drive-folder-card:hover{transform:translateY(-2px);box-shadow:0 .7rem 1.5rem rgba(57,36,22,.11)}.drive-folder-card>i{color:#e8a41e;font-size:2rem}.drive-folder-card strong,.drive-folder-card small{display:block}.drive-folder-card small{color:var(--muted)}.drive-image-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(210px,1fr));gap:1rem}.drive-image-card{overflow:hidden;background:#fff;border:1px solid var(--line);border-radius:1rem;box-shadow:0 .6rem 1.4rem rgba(57,36,22,.08);transition:transform .2s,box-shadow .2s}.drive-image-card:hover{transform:translateY(-3px);box-shadow:0 1rem 2rem rgba(57,36,22,.14)}.drive-image-button{display:block;width:100%;padding:0;background:#f4efe8;border:0}.drive-image-button img{display:block;width:100%;aspect-ratio:4/3;object-fit:cover}.drive-image-copy{padding:.85rem}.drive-image-copy strong{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.drive-image-copy small{display:block;margin-top:.25rem;color:var(--muted)}.drive-image-actions{display:grid;grid-template-columns:1fr auto;gap:.5rem;margin-top:.75rem}.drive-preview-body{display:grid;place-items:center;min-height:55vh;background:#16120f}.drive-preview-body img{max-width:100%;max-height:72vh;object-fit:contain}@media(max-width:575px){.drive-folder-grid{grid-template-columns:1fr}.drive-image-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:.65rem}.drive-image-copy{padding:.65rem}.drive-image-actions{grid-template-columns:1fr}.drive-image-actions .btn{font-size:.7rem}}</style>
<script>
document.addEventListener('DOMContentLoaded',()=>{
 const endpoint=@json(route('admin.drive-gallery.files')),uploadEndpoint=@json(route('admin.drive-gallery.upload')),grid=document.querySelector('[data-gallery-grid]'),folderGrid=document.querySelector('[data-folder-grid]'),breadcrumb=document.querySelector('[data-gallery-breadcrumb]'),status=document.querySelector('[data-gallery-status]'),refresh=document.querySelector('[data-gallery-refresh]');let library={files:[],folders:[]},currentPath='Principal';
 const escape=value=>{const node=document.createElement('div');node.textContent=value??'';return node.innerHTML};
 const size=bytes=>bytes?`${(bytes/1024/1024).toFixed(bytes>1048576?1:2)} MB`:'Tamaño no disponible';
 const render=()=>{const folders=library.folders.filter(folder=>folder.parent===currentPath),files=library.files.filter(file=>file.folder===currentPath);const parts=currentPath.split(' / ');let path='';breadcrumb.classList.remove('d-none');breadcrumb.innerHTML=parts.map((part,index)=>{path=index===0?part:`${path} / ${part}`;return `${index?'<i class="bi bi-chevron-right"></i>':''}<button type="button" data-folder-path="${encodeURIComponent(path)}">${escape(index===0?'Galería':part)}</button>`}).join('');folderGrid.innerHTML=folders.map(folder=>{const total=library.files.filter(file=>file.folder===folder.path||file.folder.startsWith(`${folder.path} / `)).length;return `<button class="drive-folder-card" type="button" data-folder-path="${encodeURIComponent(folder.path)}"><i class="bi bi-folder-fill"></i><span><strong>${escape(folder.name)}</strong><small>${total} imagen${total===1?'':'es'}</small></span></button>`}).join('');grid.innerHTML=files.map(file=>{const preview=encodeURIComponent(JSON.stringify(file));return `<article class="drive-image-card"><button class="drive-image-button" type="button" data-preview="${preview}" data-bs-toggle="modal" data-bs-target="#driveImageModal"><img src="${file.thumbnail_url}" alt="${escape(file.name)}" loading="lazy"></button><div class="drive-image-copy"><strong title="${escape(file.name)}">${escape(file.name)}</strong><small>${size(file.size)}</small><div class="drive-image-actions"><button class="btn btn-sm btn-outline-dark" type="button" data-preview="${preview}" data-bs-toggle="modal" data-bs-target="#driveImageModal"><i class="bi bi-eye me-1"></i>Ver</button><a class="btn btn-sm btn-dark" href="${file.download_url}" title="Descargar"><i class="bi bi-download"></i></a></div></div></article>`}).join('');status.hidden=folders.length>0||files.length>0;if(!status.hidden){status.className='drive-gallery-status';status.innerHTML='<i class="bi bi-folder2-open fs-2"></i>Esta carpeta está vacía.'}};
 const load=async()=>{refresh.disabled=true;status.className='drive-gallery-status';status.innerHTML='<span class="spinner-border spinner-border-sm"></span>Cargando imágenes y subcarpetas...';status.hidden=false;folderGrid.innerHTML='';grid.innerHTML='';breadcrumb.classList.add('d-none');try{const response=await fetch(endpoint,{headers:{Accept:'application/json'},cache:'no-store'}),payload=await response.json();if(!response.ok)throw new Error(payload.message||'No se pudo cargar la galería.');library=payload;const select=document.querySelector('[data-upload-folder]');if(select)select.innerHTML=`<option value="{{ config('services.drive_gallery.folder_id') }}">Galería principal</option>`+library.folders.map(folder=>`<option value="${folder.id}">${escape(folder.path.replace('Principal / ',''))}</option>`).join('');render()}catch(error){status.className='drive-gallery-status is-error';status.innerHTML=`<i class="bi bi-exclamation-triangle-fill"></i>${escape(error.message)}`}finally{refresh.disabled=false}};
 document.addEventListener('click',event=>{const folder=event.target.closest('[data-folder-path]');if(folder){currentPath=decodeURIComponent(folder.dataset.folderPath);render();return}const trigger=event.target.closest('[data-preview]');if(!trigger)return;const file=JSON.parse(decodeURIComponent(trigger.dataset.preview));document.querySelector('[data-preview-name]').textContent=file.name;const image=document.querySelector('[data-preview-image]');image.src=file.thumbnail_url;image.alt=file.name;document.querySelector('[data-preview-drive]').href=file.view_url;document.querySelector('[data-preview-download]').href=file.download_url});
 refresh.addEventListener('click',load);load();
 const uploadForm=document.querySelector('[data-upload-form]');uploadForm?.addEventListener('submit',event=>{event.preventDefault();const submit=uploadForm.querySelector('[data-upload-submit]'),wrap=uploadForm.querySelector('[data-upload-progress-wrap]'),bar=uploadForm.querySelector('[data-upload-progress]'),percent=uploadForm.querySelector('[data-upload-percent]'),message=uploadForm.querySelector('[data-upload-message]'),xhr=new XMLHttpRequest();submit.disabled=true;wrap.classList.remove('d-none');message.className='alert d-none';xhr.open('POST',uploadEndpoint);xhr.setRequestHeader('Accept','application/json');xhr.setRequestHeader('X-CSRF-TOKEN',document.querySelector('meta[name="csrf-token"]').content);xhr.upload.addEventListener('progress',progress=>{if(!progress.lengthComputable)return;const value=Math.round(progress.loaded/progress.total*100);bar.style.width=`${value}%`;percent.textContent=`${value}%`});xhr.addEventListener('load',async()=>{let payload={};try{payload=JSON.parse(xhr.responseText)}catch{}submit.disabled=false;if(xhr.status<200||xhr.status>=300){message.className='alert alert-danger';message.textContent=Object.values(payload.errors||{}).flat()[0]||payload.message||'No se pudo completar la carga.';return}document.querySelector('#driveUploadModal [data-bs-dismiss="modal"]')?.click();uploadForm.reset();bar.style.width='0';percent.textContent='0%';wrap.classList.add('d-none');await window.Swal.fire({title:'Carga completada',text:payload.message,icon:'success',confirmButtonText:'Listo'});load()});xhr.addEventListener('error',()=>{submit.disabled=false;message.className='alert alert-danger';message.textContent='Se perdió la conexión durante la carga.'});xhr.send(new FormData(uploadForm))});
});
</script>
@endsection
