@extends('layouts.app')
@section('title', 'Galería de Drive | ForjaLab')
@section('content')
<section class="admin-section"><div class="container">
    <div class="admin-header"><div><div class="eyebrow">Recursos compartidos</div><h1 class="fw-bold mt-2 mb-0">Galería de imágenes</h1><p class="text-secondary mt-2 mb-0">Consulta y descarga los archivos de Drive sin salir del sistema.</p></div><div class="d-flex gap-2 flex-wrap"><button class="btn btn-outline-dark" type="button" data-gallery-refresh><i class="bi bi-arrow-clockwise me-2"></i>Actualizar</button><a class="btn btn-dark" href="{{ $folderUrl }}" target="_blank" rel="noopener"><i class="bi bi-google me-2"></i>Abrir Drive</a></div></div>
    <div class="panel-card drive-native-gallery"><nav class="drive-breadcrumb d-none" aria-label="Carpetas" data-gallery-breadcrumb></nav><div class="drive-gallery-status" data-gallery-status><span class="spinner-border spinner-border-sm"></span>Cargando imágenes...</div><div class="drive-folder-grid" data-folder-grid></div><div class="drive-image-grid" data-gallery-grid></div></div>
</div></section>

<div class="modal fade" id="driveImageModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-xl modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h2 class="modal-title h5 fw-bold" data-preview-name>Imagen</h2><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button></div><div class="modal-body drive-preview-body"><img src="" alt="" data-preview-image></div><div class="modal-footer"><a class="btn btn-outline-dark" target="_blank" rel="noopener" data-preview-drive><i class="bi bi-box-arrow-up-right me-1"></i>Ver en Drive</a><a class="btn btn-dark" data-preview-download><i class="bi bi-download me-1"></i>Descargar</a></div></div></div></div>

<style>.drive-native-gallery{min-height:420px}.drive-gallery-status{display:flex;align-items:center;justify-content:center;gap:.65rem;min-height:320px;color:var(--muted);font-weight:800}.drive-gallery-status.is-error{color:#a52d20}.drive-breadcrumb{display:flex;align-items:center;gap:.4rem;margin-bottom:1.2rem;padding:.75rem 1rem;background:#fff8ed;border:1px solid var(--line);border-radius:.8rem}.drive-breadcrumb button{padding:0;color:var(--forge-brown);font-weight:800;background:none;border:0}.drive-breadcrumb i{color:var(--muted);font-size:.72rem}.drive-folder-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:.8rem;margin-bottom:1.2rem}.drive-folder-card{display:flex;align-items:center;gap:.8rem;padding:1rem;text-align:left;background:linear-gradient(135deg,#fff8e9,#fff);border:1px solid #ead8bc;border-radius:.9rem;transition:transform .2s,box-shadow .2s}.drive-folder-card:hover{transform:translateY(-2px);box-shadow:0 .7rem 1.5rem rgba(57,36,22,.11)}.drive-folder-card>i{color:#e8a41e;font-size:2rem}.drive-folder-card strong,.drive-folder-card small{display:block}.drive-folder-card small{color:var(--muted)}.drive-image-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(210px,1fr));gap:1rem}.drive-image-card{overflow:hidden;background:#fff;border:1px solid var(--line);border-radius:1rem;box-shadow:0 .6rem 1.4rem rgba(57,36,22,.08);transition:transform .2s,box-shadow .2s}.drive-image-card:hover{transform:translateY(-3px);box-shadow:0 1rem 2rem rgba(57,36,22,.14)}.drive-image-button{display:block;width:100%;padding:0;background:#f4efe8;border:0}.drive-image-button img{display:block;width:100%;aspect-ratio:4/3;object-fit:cover}.drive-image-copy{padding:.85rem}.drive-image-copy strong{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.drive-image-copy small{display:block;margin-top:.25rem;color:var(--muted)}.drive-image-actions{display:grid;grid-template-columns:1fr auto;gap:.5rem;margin-top:.75rem}.drive-preview-body{display:grid;place-items:center;min-height:55vh;background:#16120f}.drive-preview-body img{max-width:100%;max-height:72vh;object-fit:contain}@media(max-width:575px){.drive-folder-grid{grid-template-columns:1fr}.drive-image-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:.65rem}.drive-image-copy{padding:.65rem}.drive-image-actions{grid-template-columns:1fr}.drive-image-actions .btn{font-size:.7rem}}</style>
<script>
document.addEventListener('DOMContentLoaded',()=>{
 const endpoint=@json(route('admin.drive-gallery.files')),grid=document.querySelector('[data-gallery-grid]'),folderGrid=document.querySelector('[data-folder-grid]'),breadcrumb=document.querySelector('[data-gallery-breadcrumb]'),status=document.querySelector('[data-gallery-status]'),refresh=document.querySelector('[data-gallery-refresh]');let library={files:[],folders:[]},currentPath='Principal';
 const escape=value=>{const node=document.createElement('div');node.textContent=value??'';return node.innerHTML};
 const size=bytes=>bytes?`${(bytes/1024/1024).toFixed(bytes>1048576?1:2)} MB`:'Tamaño no disponible';
 const render=()=>{const folders=library.folders.filter(folder=>folder.parent===currentPath),files=library.files.filter(file=>file.folder===currentPath);const parts=currentPath.split(' / ');let path='';breadcrumb.classList.remove('d-none');breadcrumb.innerHTML=parts.map((part,index)=>{path=index===0?part:`${path} / ${part}`;return `${index?'<i class="bi bi-chevron-right"></i>':''}<button type="button" data-folder-path="${encodeURIComponent(path)}">${escape(index===0?'Galería':part)}</button>`}).join('');folderGrid.innerHTML=folders.map(folder=>{const total=library.files.filter(file=>file.folder===folder.path||file.folder.startsWith(`${folder.path} / `)).length;return `<button class="drive-folder-card" type="button" data-folder-path="${encodeURIComponent(folder.path)}"><i class="bi bi-folder-fill"></i><span><strong>${escape(folder.name)}</strong><small>${total} imagen${total===1?'':'es'}</small></span></button>`}).join('');grid.innerHTML=files.map(file=>{const preview=encodeURIComponent(JSON.stringify(file));return `<article class="drive-image-card"><button class="drive-image-button" type="button" data-preview="${preview}" data-bs-toggle="modal" data-bs-target="#driveImageModal"><img src="${file.thumbnail_url}" alt="${escape(file.name)}" loading="lazy"></button><div class="drive-image-copy"><strong title="${escape(file.name)}">${escape(file.name)}</strong><small>${size(file.size)}</small><div class="drive-image-actions"><button class="btn btn-sm btn-outline-dark" type="button" data-preview="${preview}" data-bs-toggle="modal" data-bs-target="#driveImageModal"><i class="bi bi-eye me-1"></i>Ver</button><a class="btn btn-sm btn-dark" href="${file.download_url}" title="Descargar"><i class="bi bi-download"></i></a></div></div></article>`}).join('');status.hidden=folders.length>0||files.length>0;if(!status.hidden){status.className='drive-gallery-status';status.innerHTML='<i class="bi bi-folder2-open fs-2"></i>Esta carpeta está vacía.'}};
 const load=async()=>{refresh.disabled=true;status.className='drive-gallery-status';status.innerHTML='<span class="spinner-border spinner-border-sm"></span>Cargando imágenes y subcarpetas...';status.hidden=false;folderGrid.innerHTML='';grid.innerHTML='';breadcrumb.classList.add('d-none');try{const response=await fetch(endpoint,{headers:{Accept:'application/json'},cache:'no-store'}),payload=await response.json();if(!response.ok)throw new Error(payload.message||'No se pudo cargar la galería.');library=payload;render()}catch(error){status.className='drive-gallery-status is-error';status.innerHTML=`<i class="bi bi-exclamation-triangle-fill"></i>${escape(error.message)}`}finally{refresh.disabled=false}};
 document.addEventListener('click',event=>{const folder=event.target.closest('[data-folder-path]');if(folder){currentPath=decodeURIComponent(folder.dataset.folderPath);render();return}const trigger=event.target.closest('[data-preview]');if(!trigger)return;const file=JSON.parse(decodeURIComponent(trigger.dataset.preview));document.querySelector('[data-preview-name]').textContent=file.name;const image=document.querySelector('[data-preview-image]');image.src=file.thumbnail_url;image.alt=file.name;document.querySelector('[data-preview-drive]').href=file.view_url;document.querySelector('[data-preview-download]').href=file.download_url});
 refresh.addEventListener('click',load);load();
});
</script>
@endsection
