@extends('layouts.app')
@section('title','Variantes '.$product->name.' | ForjaLab')
@section('content')
<section class="admin-section"><div class="container"><div class="admin-header"><div><div class="eyebrow">Inventario por variante</div><h1 class="fw-bold mt-2 mb-0">{{ $product->name }}</h1><p class="text-secondary mt-2 mb-0">Combina color y talla; cada renglón conserva sus propias existencias y alerta.</p></div><a class="btn btn-outline-dark" href="{{ route('admin.inventory.index') }}"><i class="bi bi-arrow-left me-2"></i>Inventario</a></div>
@if(session('status'))<div class="alert alert-success"><i class="bi bi-check-circle-fill me-2"></i>{{ session('status') }}</div>@endif
<form method="POST" action="{{ route('admin.inventory.variants.update',$product) }}" class="panel-card">@csrf @method('PUT')<div class="variant-matrix-heading"><div><h2 class="h5 fw-bold mb-1"><i class="bi bi-grid-3x3-gap-fill me-2 text-primary"></i>Matriz de colores y tallas</h2><small class="text-secondary">Para productos de un solo atributo deja vacía la talla o el color.</small></div>@can('catalog.manage')<button class="btn btn-primary" type="button" data-add-variant><i class="bi bi-plus-circle me-2"></i>Agregar variante</button>@endcan</div><div class="variant-matrix" data-variant-list><div class="variant-matrix-header"><span>Color</span><span>Talla</span><span>SKU</span><span>Existencia</span><span>Mínimo</span><span>Activa</span><span></span></div>@foreach($product->variants as $index=>$variant)<div class="variant-row" data-variant-row><input type="hidden" name="variants[{{ $index }}][id]" value="{{ $variant->id }}"><input class="form-control" name="variants[{{ $index }}][color]" value="{{ $variant->color }}" placeholder="Ej. Negro"><input class="form-control" name="variants[{{ $index }}][size]" value="{{ $variant->size }}" placeholder="Ej. M"><input class="form-control" name="variants[{{ $index }}][sku]" value="{{ $variant->sku }}" placeholder="Automático"><input class="form-control" type="number" min="0" name="variants[{{ $index }}][stock]" value="{{ $variant->stock }}" required><input class="form-control" type="number" min="0" name="variants[{{ $index }}][minimum_stock]" value="{{ $variant->minimum_stock }}" required><label class="form-switch-wrap"><input class="form-check-input" type="checkbox" name="variants[{{ $index }}][is_active]" value="1" @checked($variant->is_active)><span>{{ $variant->is_active?'Sí':'No' }}</span></label><button class="btn btn-outline-danger" type="button" data-remove-variant><i class="bi bi-x-lg"></i></button></div>@endforeach</div>@can('catalog.manage')<div class="d-flex justify-content-end mt-4"><button class="btn btn-dark btn-lg"><i class="bi bi-floppy-fill me-2"></i>Guardar matriz</button></div>@endcan</form></div></section>
<template data-variant-template><div class="variant-row" data-variant-row><input class="form-control" name="variants[__INDEX__][color]" placeholder="Ej. Negro"><input class="form-control" name="variants[__INDEX__][size]" placeholder="Ej. M"><input class="form-control" name="variants[__INDEX__][sku]" placeholder="Automático"><input class="form-control" type="number" min="0" name="variants[__INDEX__][stock]" value="0" required><input class="form-control" type="number" min="0" name="variants[__INDEX__][minimum_stock]" value="2" required><label class="form-switch-wrap"><input class="form-check-input" type="checkbox" name="variants[__INDEX__][is_active]" value="1" checked><span>Sí</span></label><button class="btn btn-outline-danger" type="button" data-remove-variant><i class="bi bi-x-lg"></i></button></div></template>
<script>document.addEventListener('DOMContentLoaded',()=>{const list=document.querySelector('[data-variant-list]'),template=document.querySelector('[data-variant-template]');let index={{ $product->variants->count() }};document.querySelector('[data-add-variant]')?.addEventListener('click',()=>{list.insertAdjacentHTML('beforeend',template.innerHTML.replaceAll('__INDEX__',index++))});list.addEventListener('click',event=>{const button=event.target.closest('[data-remove-variant]');if(button)button.closest('[data-variant-row]').remove()});list.addEventListener('change',event=>{if(event.target.matches('.form-check-input'))event.target.nextElementSibling.textContent=event.target.checked?'Sí':'No'})});</script>
<script>document.addEventListener('DOMContentLoaded',()=>{const paint=row=>{if(!row)return;const stock=Number(row.querySelector('input[name$="[stock]"]')?.value||0),minimum=Number(row.querySelector('input[name$="[minimum_stock]"]')?.value||0);row.classList.toggle('is-out',stock===0);row.classList.toggle('is-low',stock>0&&stock<=minimum);row.title=stock===0?'Variante agotada':(stock<=minimum?'Variante con stock bajo':'')};document.querySelectorAll('[data-variant-row]').forEach(paint);document.querySelector('[data-variant-list]')?.addEventListener('input',event=>paint(event.target.closest('[data-variant-row]')))})</script>
@endsection
