@extends('layouts.app')
@section('title', 'Clientes y prospectos | ForjaLab')
@section('content')
<section class="admin-section"><div class="container">
    <div class="admin-header"><div><div class="eyebrow">Relación comercial</div><h1 class="fw-bold mt-2 mb-0">Clientes y prospectos</h1></div>@if($pendingCount)<span class="lead-pending-counter"><i class="bi bi-bell-fill"></i>{{ $pendingCount }} por contactar</span>@endif</div>
    <div class="lead-filter-bar panel-card mb-4"><form class="row g-2 align-items-end" method="GET"><div class="col-md"><label class="form-label"><i class="bi bi-search me-1"></i>Buscar</label><input class="form-control" name="q" value="{{ $search }}" placeholder="Nombre, correo, teléfono o empresa"></div><div class="col-md-3"><label class="form-label"><i class="bi bi-person-badge me-1"></i>Tipo</label><select class="form-select" name="type"><option value="">Todos</option><option value="prospects" @selected($type==='prospects')>Prospectos web activos</option><option value="customers" @selected($type==='customers')>Clientes directos</option></select></div><div class="col-md-3"><label class="form-label"><i class="bi bi-flag-fill me-1"></i>Estado</label><select class="form-select" name="status"><option value="">Todos los estados</option>@foreach($statuses as $value=>$label)<option value="{{ $value }}" @selected($status===$value)>{{ $label }}</option>@endforeach</select></div><div class="col-md-auto"><button class="btn btn-dark w-100"><i class="bi bi-funnel-fill me-1"></i>Filtrar</button></div>@if($search || $type || $status)<div class="col-md-auto"><a class="btn btn-outline-secondary w-100" href="{{ route('admin.customers.index') }}"><i class="bi bi-x-circle me-1"></i>Limpiar</a></div>@endif</form></div>
    <div class="customer-admin-grid">
    @forelse($customers as $customer)
        @php($customerEditData = $customer->only(['id', 'name', 'company', 'phone', 'whatsapp', 'email', 'address', 'interested_service', 'lead_status', 'notes']))
        <article class="customer-admin-card {{ $customer->lead_source === 'website_popup' ? 'web-lead' : '' }}" data-customer-card="{{ $customer->id }}">
            <div class="customer-admin-head"><span class="customer-avatar" data-customer-avatar>{{ Str::upper(Str::substr($customer->name,0,1)) }}</span><div><h2 data-customer-name>{{ $customer->name }}</h2><small data-customer-company>{{ $customer->company ?: 'Persona particular' }}</small></div>@if($customer->lead_source === 'website_popup')<span class="badge text-bg-warning"><i class="bi bi-globe2 me-1"></i>Prospecto web</span>@else<span class="badge text-bg-light">Cliente</span>@endif</div>
            <div class="customer-contact-list"><a href="{{ $customer->email ? 'mailto:'.$customer->email : '#' }}" data-customer-email><i class="bi bi-envelope-fill"></i><span>{{ $customer->email ?: 'Sin correo' }}</span></a><a href="{{ $customer->phone ? 'tel:'.$customer->phone : '#' }}" data-customer-phone><i class="bi bi-telephone-fill"></i><span>{{ $customer->phone ?: 'Sin teléfono' }}</span></a><a class="{{ $customer->whatsapp ? '' : 'd-none' }}" href="https://wa.me/{{ preg_replace('/\D+/','',$customer->whatsapp) }}" target="_blank" rel="noopener" data-customer-whatsapp><i class="bi bi-whatsapp"></i><span>{{ $customer->whatsapp }}</span></a></div>
            <div class="customer-interest {{ $customer->interested_service ? '' : 'd-none' }}" data-customer-interest><small>Servicio de interés</small><strong>{{ str($customer->interested_service)->replace('_',' ')->title() }}</strong></div>
            <div class="customer-admin-meta"><span><i class="bi bi-receipt"></i>{{ $customer->orders_count }} pedidos</span><span><i class="bi bi-calendar3"></i>{{ $customer->created_at->format('d/m/Y H:i') }}</span></div>
            @can('customers.manage')<button class="btn btn-sm btn-outline-dark w-100" type="button" data-customer-edit data-customer-id="{{ $customer->id }}" data-bs-toggle="modal" data-bs-target="#customerEditModal" data-update-url="{{ route('admin.customers.update',$customer) }}"><i class="bi bi-pencil-square me-1"></i>Editar cliente</button><script type="application/json" id="customerData{{ $customer->id }}">@json($customerEditData)</script>@endcan
        </article>
    @empty<div class="panel-card text-center py-5"><i class="bi bi-people fs-1 text-secondary"></i><p class="mt-3 mb-0">No encontramos clientes con estos filtros.</p></div>@endforelse
    </div><div class="mt-4">{{ $customers->links() }}</div>
</div></section>

@can('customers.manage')
<div class="modal fade" id="customerEditModal" tabindex="-1" aria-labelledby="customerEditTitle" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable"><div class="modal-content">
    <form data-customer-edit-form><div class="modal-header"><div class="d-flex align-items-center gap-3"><span class="customer-modal-icon"><i class="bi bi-person-vcard-fill"></i></span><div><div class="eyebrow">Edición rápida</div><h2 class="modal-title h4 fw-bold mb-0" id="customerEditTitle">Editar cliente</h2></div></div><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button></div>
    <div class="modal-body"><div class="alert d-none" role="alert" data-customer-message></div><div class="row g-3">
        <div class="col-md-6"><label class="form-label"><i class="bi bi-person-fill me-1"></i>Nombre *</label><input class="form-control" name="name" required maxlength="160"></div><div class="col-md-6"><label class="form-label"><i class="bi bi-building-fill me-1"></i>Empresa</label><input class="form-control" name="company" maxlength="160"></div>
        <div class="col-md-6"><label class="form-label"><i class="bi bi-telephone-fill me-1"></i>Teléfono</label><input class="form-control" name="phone" maxlength="30"></div><div class="col-md-6"><label class="form-label"><i class="bi bi-whatsapp me-1"></i>WhatsApp</label><input class="form-control" name="whatsapp" maxlength="30"></div>
        <div class="col-md-6"><label class="form-label"><i class="bi bi-envelope-fill me-1"></i>Correo</label><input class="form-control" name="email" type="email" maxlength="160"></div><div class="col-md-6"><label class="form-label"><i class="bi bi-flag-fill me-1"></i>Estado</label><select class="form-select" name="lead_status" required>@foreach($statuses as $value=>$label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></div>
        <div class="col-md-6"><label class="form-label"><i class="bi bi-stars me-1"></i>Servicio de interés</label><select class="form-select" name="interested_service"><option value="">Sin especificar</option><option value="biker_tag">Biker Tag QR</option><option value="dog_tag">Dog Tag QR</option><option value="sublimation">Sublimación o DTF</option><option value="laser">Grabado y corte láser</option><option value="catalog">Productos del catálogo</option><option value="corporate">Pedido corporativo</option><option value="other">Otro proyecto</option></select></div><div class="col-md-6"><label class="form-label"><i class="bi bi-geo-alt-fill me-1"></i>Dirección</label><textarea class="form-control" name="address" rows="1" maxlength="1000"></textarea></div>
        <div class="col-12"><label class="form-label"><i class="bi bi-chat-left-text-fill me-1"></i>Notas</label><textarea class="form-control" name="notes" rows="2" maxlength="3000"></textarea></div>
    </div></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal"><i class="bi bi-x-lg me-1"></i>Cancelar</button><button class="btn btn-dark" type="submit" data-customer-save><i class="bi bi-check2-circle me-1"></i>Guardar cambios</button></div></form>
</div></div></div>
<script>
document.addEventListener('DOMContentLoaded',()=>{
 const form=document.querySelector('[data-customer-edit-form]'),message=form?.querySelector('[data-customer-message]'),save=form?.querySelector('[data-customer-save]');let url='',card=null;
 const labels={biker_tag:'Biker Tag QR',dog_tag:'Dog Tag QR',sublimation:'Sublimación o DTF',laser:'Grabado y corte láser',catalog:'Productos del catálogo',corporate:'Pedido corporativo',other:'Otro proyecto'};
 document.querySelectorAll('[data-customer-edit]').forEach(button=>button.addEventListener('click',()=>{const customer=JSON.parse(document.querySelector(`#customerData${button.dataset.customerId}`).textContent);url=button.dataset.updateUrl;card=document.querySelector(`[data-customer-card="${customer.id}"]`);Object.entries(customer).forEach(([key,value])=>{const field=form.elements.namedItem(key);if(field)field.value=value??''});message.className='alert d-none';message.textContent=''}));
 form?.addEventListener('submit',async event=>{event.preventDefault();save.disabled=true;message.className='alert d-none';window.Swal?.fire({title:'Guardando cliente',text:'Estamos actualizando la información.',allowOutsideClick:false,allowEscapeKey:false,didOpen:()=>window.Swal.showLoading()});try{const data=new FormData(form);data.append('_method','PUT');const response=await fetch(url,{method:'POST',headers:{Accept:'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content},body:data});const payload=await response.json();if(!response.ok)throw new Error(Object.values(payload.errors||{}).flat()[0]||payload.message||'No se pudo guardar.');const c=payload.customer;card.querySelector('[data-customer-name]').textContent=c.name;card.querySelector('[data-customer-avatar]').textContent=c.name.charAt(0).toUpperCase();card.querySelector('[data-customer-company]').textContent=c.company||'Persona particular';const email=card.querySelector('[data-customer-email]');email.href=c.email?`mailto:${c.email}`:'#';email.querySelector('span').textContent=c.email||'Sin correo';const phone=card.querySelector('[data-customer-phone]');phone.href=c.phone?`tel:${c.phone}`:'#';phone.querySelector('span').textContent=c.phone||'Sin teléfono';const whatsapp=card.querySelector('[data-customer-whatsapp]');whatsapp.classList.toggle('d-none',!c.whatsapp);whatsapp.href=`https://wa.me/${(c.whatsapp||'').replace(/\D/g,'')}`;whatsapp.querySelector('span').textContent=c.whatsapp||'';const interest=card.querySelector('[data-customer-interest]');interest.classList.toggle('d-none',!c.interested_service);interest.querySelector('strong').textContent=labels[c.interested_service]||'';document.querySelector(`#customerData${c.id}`).textContent=JSON.stringify(c);document.querySelector('#customerEditModal [data-bs-dismiss="modal"]')?.click();await window.Swal?.fire({title:'Cliente actualizado',text:payload.message,icon:'success',confirmButtonText:'Listo',customClass:{popup:'forjalab-swal',confirmButton:'btn btn-dark px-4'},buttonsStyling:false})}catch(error){message.className='alert alert-danger';message.textContent=error.message;await window.Swal?.fire({title:'No se pudo guardar',text:error.message,icon:'error',confirmButtonText:'Revisar',customClass:{popup:'forjalab-swal',confirmButton:'btn btn-dark px-4'},buttonsStyling:false})}finally{save.disabled=false}});
});
</script>
<style>.customer-modal-icon{display:grid;place-items:center;width:48px;height:48px;color:#fff;font-size:1.35rem;background:linear-gradient(135deg,var(--forge-orange),var(--forge-green));border-radius:.9rem;box-shadow:0 .5rem 1rem rgba(57,36,22,.16)}#customerEditModal .form-label i{color:var(--forge-orange)}#customerEditModal .modal-content{overflow:hidden;border:0;border-radius:1.1rem;box-shadow:0 1.5rem 4rem rgba(31,20,12,.24)}#customerEditModal .modal-header{background:linear-gradient(135deg,#fff8ed,#fff)}</style>
@endcan
@endsection
