<!doctype html><html lang="es"><head><meta charset="utf-8"><title>{{ $order->folio }}</title><style>
@page{margin:34px}body{font-family:DejaVu Sans,sans-serif;color:#29241e;font-size:12px}.header{border-bottom:4px solid #e87318;padding-bottom:16px;margin-bottom:24px}.brand-wrap{display:table}.brand-logo{display:table-cell;width:54px;height:54px;object-fit:contain;vertical-align:middle}.brand-copy{display:table-cell;padding-left:10px;vertical-align:middle}.brand{font-size:26px;font-weight:bold;color:#e87318}.folio{float:right;text-align:right}.muted{color:#746c62}.cols{width:100%;margin-bottom:24px}.cols td{width:50%;vertical-align:top}.box{background:#f6f1e8;padding:14px;border-radius:8px}table.items{width:100%;border-collapse:collapse;margin-top:12px}table.items th{background:#263f2c;color:white;text-align:left;padding:9px}table.items td{padding:9px;border-bottom:1px solid #ddd;vertical-align:middle}.image-cell{width:58px}.product-image{width:52px;height:52px;object-fit:cover;border-radius:7px}.image-placeholder{width:50px;height:50px;line-height:50px;text-align:center;background:#f2eadc;color:#9a8067;border:1px solid #dfd2c0;border-radius:7px;font-size:20px}.right{text-align:right}.totals{width:43%;margin:20px 0 20px auto}.totals td{padding:5px}.grand td{font-size:16px;font-weight:bold;border-top:2px solid #29241e}.balance td{font-weight:bold;color:#c54d1d}.notes{margin-top:20px;border:1px solid #ddd;padding:12px}.footer{position:fixed;bottom:0;width:100%;text-align:center;color:#777;font-size:9px}
</style></head><body>
<div class="header"><div class="folio"><strong>PEDIDO {{ $order->folio }}</strong><br><span class="muted">Fecha: {{ $order->ordered_at->format('d/m/Y') }}</span></div><div class="brand-wrap">@if($logoSource)<img class="brand-logo" src="{{ $logoSource }}" alt="ForjaLab">@endif<div class="brand-copy"><div class="brand">ForjaLab</div><div>Productos personalizados · Ciudad de México</div></div></div></div>
<table class="cols"><tr><td><div class="box"><strong>CLIENTE</strong><br><br><strong>{{ $order->customer->name }}</strong><br>{{ $order->customer->phone }}<br>{{ $order->customer->email }}<br>{{ $order->customer->address }}</div></td><td style="padding-left:15px"><div class="box"><strong>DATOS DEL PEDIDO</strong><br><br>Estado: {{ \App\Models\Order::STATUSES[$order->status] }}<br>Entrega estimada: {{ $order->delivery_at?->format('d/m/Y') ?: 'Por definir' }}<br>Atendió: {{ $order->creator?->name ?: 'ForjaLab' }}</div></td></tr></table>
<strong>RESUMEN DE PRODUCTOS Y PAQUETES</strong><table class="items"><thead><tr><th></th><th>Concepto</th><th>Cant.</th><th class="right">Precio unitario</th><th class="right">Importe</th></tr></thead><tbody>@foreach($order->items as $item)<tr><td class="image-cell">@if($item->pdf_image_source)<img class="product-image" src="{{ $item->pdf_image_source }}" alt="">@else<div class="image-placeholder">{{ $item->item_type === 'bundle' ? 'P' : 'F' }}</div>@endif</td><td><strong>{{ $item->product_name }}</strong>@if($item->item_type === 'bundle')<br><span class="muted">Paquete incluye:<br>{!! nl2br(e($item->contents_snapshot)) !!}</span>@endif</td><td>{{ $item->quantity }}</td><td class="right">${{ number_format($item->unit_price,2) }}</td><td class="right">${{ number_format($item->line_total,2) }}</td></tr>@endforeach</tbody></table>
<table class="totals"><tr><td>Subtotal</td><td class="right">${{ number_format($order->subtotal,2) }}</td></tr><tr><td>Descuento</td><td class="right">-${{ number_format($order->discount_amount,2) }}</td></tr><tr><td>Envío</td><td class="right">${{ number_format($order->shipping_cost,2) }}</td></tr><tr class="grand"><td>Total</td><td class="right">${{ number_format($order->total,2) }} MXN</td></tr><tr><td>Anticipo pagado</td><td class="right">${{ number_format($order->advance_payment,2) }}</td></tr><tr class="balance"><td>Saldo pendiente</td><td class="right">${{ number_format($order->balance_due,2) }}</td></tr></table>
@if($order->observations)<div class="notes"><strong>OBSERVACIONES</strong><br><br>{{ $order->observations }}</div>@endif
<p class="muted" style="margin-top:28px">Este documento es el resumen formal del pedido. Conserva el folio para cualquier aclaración.</p><div class="footer">ForjaLab · WhatsApp 55 6444 2949 · forjalab.com.mx</div>
</body></html>
