@extends('layouts.app')
@section('title', $order->folio.' | ForjaLab')
@section('content')
<section class="admin-section"><div class="container">
    <div class="admin-header"><div><div class="eyebrow">Pedido {{ $order->folio }}</div><h1 class="fw-bold mt-2 mb-0">{{ $order->customer->name }}</h1></div><div class="d-flex gap-2 flex-wrap"><a class="btn btn-outline-dark" href="{{ route('admin.orders.pdf', $order) }}"><i class="bi bi-file-earmark-pdf me-2"></i>Descargar PDF</a>@can('orders.manage')<a class="btn btn-dark" href="{{ route('admin.orders.edit', $order) }}"><i class="bi bi-pencil me-2"></i>Editar</a>@endcan</div></div>
        <div class="row g-4"><div class="col-lg-8"><div class="panel-card"><div class="d-flex justify-content-between mb-3"><h2 class="h5 fw-bold">Productos y paquetes</h2><span class="badge text-bg-dark">{{ \App\Models\Order::STATUSES[$order->status] }}</span></div><div class="table-responsive"><table class="table"><thead><tr><th>Concepto</th><th>Cantidad</th><th>Precio</th><th class="text-end">Importe</th></tr></thead><tbody>@foreach($order->items as $item)<tr><td><strong>{{ $item->product_name }}</strong>@if($item->item_type === 'bundle')<span class="badge text-bg-success ms-1">Paquete</span><small class="d-block text-secondary mt-1" style="white-space:pre-line">Incluye: {{ $item->contents_snapshot }}</small>@endif</td><td>{{ $item->quantity }}</td><td>${{ number_format($item->unit_price, 2) }}</td><td class="text-end">${{ number_format($item->line_total, 2) }}</td></tr>@endforeach</tbody></table></div>
        <div class="order-totals ms-auto"><div><span>Subtotal</span><strong>${{ number_format($order->subtotal, 2) }}</strong></div><div><span>Descuento</span><strong>-${{ number_format($order->discount_amount, 2) }}</strong></div><div><span>Envío</span><strong>${{ number_format($order->shipping_cost, 2) }}</strong></div><div class="total"><span>Total</span><strong>${{ number_format($order->total, 2) }}</strong></div><div><span>Anticipo pagado</span><strong>${{ number_format($order->advance_payment, 2) }}</strong></div><div class="balance"><span>Saldo pendiente</span><strong>${{ number_format($order->balance_due, 2) }}</strong></div></div></div></div>
    <div class="col-lg-4"><div class="panel-card mb-4"><h2 class="h5 fw-bold">Cliente</h2><p class="mb-1 fw-bold">{{ $order->customer->name }}</p><p class="mb-1">{{ $order->customer->phone ?: 'Sin teléfono' }}</p><p class="mb-1">{{ $order->customer->email }}</p><p class="mb-0 text-secondary">{{ $order->customer->address }}</p></div><div class="panel-card"><h2 class="h5 fw-bold">Detalles</h2><p><strong>Pedido:</strong> {{ $order->ordered_at->format('d/m/Y') }}</p><p><strong>Entrega:</strong> {{ $order->delivery_at?->format('d/m/Y') ?: 'Por definir' }}</p><p class="mb-0"><strong>Observaciones:</strong><br>{{ $order->observations ?: 'Sin observaciones' }}</p></div></div></div>
</div></section>
@endsection
