@php
    $shipmentDraft = $shipment ?: new \App\Models\Shipment(['method' => 'skydropx']);
    $shipmentDraft->setRelation('order', $order);
    $shipmentEligible = in_array($order->status, ['in_progress', 'ready', 'delivered'], true);
@endphp
<section class="panel-card order-shipment-panel mt-4" id="shipment-panel">
    <div class="d-flex justify-content-between align-items-start gap-3 flex-wrap mb-4">
        <div><div class="eyebrow">Logística integrada</div><h2 class="h4 fw-bold mt-2 mb-1"><i class="bi bi-box-seam-fill text-primary me-2"></i>Guía y seguimiento Skydropx</h2><p class="text-secondary mb-0">Cotiza, vincula la guía y administra el seguimiento sin salir del pedido.</p></div>
        @if($shipment)
            <div class="d-flex gap-2 flex-wrap"><span class="shipment-inline-status"><i class="bi bi-activity"></i>{{ \App\Models\Shipment::STATUSES[$shipment->status] ?? $shipment->status }}</span>@if($shipment->label_url)<a class="btn btn-sm btn-dark" href="{{ $shipment->label_url }}" target="_blank" rel="noopener"><i class="bi bi-file-earmark-arrow-down-fill me-1"></i>Descargar guía</a>@endif<a class="btn btn-sm btn-outline-primary" href="{{ $shipment->public_url }}" target="_blank" rel="noopener"><i class="bi bi-eye me-1"></i>Vista del cliente</a></div>
        @endif
    </div>

    @if(!$shipmentEligible && !$shipment)
        <div class="alert alert-info mb-0"><i class="bi bi-info-circle-fill me-2"></i>Guarda el pedido con estado <strong>En producción</strong> o <strong>Listo para entregar</strong> para habilitar la vinculación de la guía.</div>
    @else
        <form method="POST" action="{{ $shipment ? route('admin.shipments.update', $shipment) : route('admin.shipments.store', $order) }}" data-inline-shipment-form>
            @csrf
            @if($shipment) @method('PUT') @else <input type="hidden" name="return_to" value="order_edit"> @endif
            @if($shipment)
                <div class="row g-3 mb-3"><div class="col-md-4"><label class="form-label"><i class="bi bi-signpost-split me-1"></i>Estado del seguimiento</label><select class="form-select" name="status">@foreach(\App\Models\Shipment::STATUSES as $value => $label)<option value="{{ $value }}" @selected($shipment->status === $value)>{{ $label }}</option>@endforeach</select></div>@if($shipment->tracking_number)<div class="col-md-4"><label class="form-label">Número de guía</label><div class="shipment-tracking-value"><i class="bi bi-upc-scan"></i>{{ $shipment->tracking_number }}</div></div>@endif @if($shipment->tracking_url)<div class="col-md-4 d-flex align-items-end"><a class="btn btn-outline-dark w-100" href="{{ $shipment->tracking_url }}" target="_blank" rel="noopener"><i class="bi bi-box-arrow-up-right me-2"></i>Rastrear paquete</a></div>@endif</div>
            @endif
            @include('admin.shipments.partials.fields', ['shipment' => $shipmentDraft])
            <div class="d-flex gap-2 flex-wrap mt-4">
                <button class="btn btn-dark" type="submit"><i class="bi bi-floppy-fill me-2"></i>{{ $shipment ? 'Guardar seguimiento' : 'Crear seguimiento' }}</button>
                @if(!$shipment || ($shipment->method === 'skydropx' && !$shipment->skydropx_shipment_id))
                    <button class="btn btn-primary" type="button" data-inline-quote><i class="bi bi-calculator-fill me-2"></i>Cotizar con Skydropx</button>
                    <button class="btn btn-outline-primary" type="button" data-assign-guide-button data-bs-toggle="modal" data-bs-target="#assignGuideModal"><i class="bi bi-link-45deg me-2"></i>Asignar guía existente</button>
                @endif
            </div>
            @unless($shipment)
                <input type="hidden" name="rate_id" data-rate-id><input type="hidden" name="rate_carrier" data-rate-carrier><input type="hidden" name="rate_service" data-rate-service><input type="hidden" name="rate_price" data-rate-price>
            @endunless
        </form>
        <div class="alert d-none mt-3 mb-0" data-inline-shipping-message></div>
        <div class="shipping-rates mt-3" data-inline-rates></div>
    @endif
</section>

@if($shipmentEligible && (!$shipment || !$shipment->skydropx_shipment_id))
<div class="modal fade" id="assignGuideModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header"><div><div class="eyebrow">Skydropx</div><h2 class="modal-title h4 fw-bold">Asignar guía existente</h2><p class="text-secondary mb-0">Las guías vinculadas están identificadas para evitar duplicados.</p></div><button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Cerrar"></button></div><div class="modal-body"><div class="input-group mb-3"><span class="input-group-text"><i class="bi bi-search"></i></span><input class="form-control" type="search" placeholder="Buscar guía, paquetería, destinatario o pedido…" data-guide-search></div><div class="guide-assignment-list" data-guide-assignment-list><div class="text-center py-5 text-secondary"><span class="spinner-border spinner-border-sm me-2"></span>Consultando guías de Skydropx…</div></div></div></div></div></div>
@endif

<style>.order-shipment-panel{scroll-margin-top:6rem;border-top:4px solid #6f42c1}.shipment-inline-status{display:inline-flex;align-items:center;gap:.4rem;padding:.45rem .7rem;color:#4c2882;font-size:.75rem;font-weight:850;background:#e5d9f7;border-radius:999px}.shipment-tracking-value{display:flex;align-items:center;gap:.55rem;min-height:38px;padding:.45rem .7rem;font-weight:850;background:#f4f0eb;border-radius:.55rem}.guide-assignment-list{display:grid;gap:.75rem}.guide-assignment-item{display:grid;grid-template-columns:42px 1fr auto;align-items:center;gap:1rem;padding:1rem;background:#fff;border:1px solid var(--line);border-radius:.9rem}.guide-assignment-item>i{display:grid;place-items:center;width:42px;height:42px;color:#fff;font-size:1.1rem;background:#6f42c1;border-radius:.75rem}.guide-assignment-item strong,.guide-assignment-item span,.guide-assignment-item small{display:block}.guide-assignment-item span,.guide-assignment-item small{color:var(--muted)}@media(max-width:575px){.guide-assignment-item{grid-template-columns:36px 1fr}.guide-assignment-item .btn{grid-column:1/-1}}</style>
<style>.guide-assignment-item.is-assigned{background:#f3f8f4;border-color:#badbcc}.guide-assignment-item.is-assigned>i{background:#198754}.guide-assigned-badge{display:inline-flex!important;align-items:center;gap:.35rem;width:max-content;margin-top:.35rem;padding:.28rem .5rem!important;color:#0f5132!important;font-size:.68rem;font-weight:850;background:#d1e7dd;border-radius:999px}</style>

@if($shipmentEligible || $shipment)
<script>
document.addEventListener('DOMContentLoaded',()=>{
    const form=document.querySelector('[data-inline-shipment-form]'),quoteButton=document.querySelector('[data-inline-quote]'),rates=document.querySelector('[data-inline-rates]'),messageBox=document.querySelector('[data-inline-shipping-message]'),assignButton=document.querySelector('[data-assign-guide-button]'),guideList=document.querySelector('[data-guide-assignment-list]'),guideSearch=document.querySelector('[data-guide-search]');
    if(!form||!quoteButton)return;
    const isExisting=@json((bool) $shipment),quoteUrl=@json($shipment ? route('admin.shipments.quote-rates',$shipment) : route('admin.shipments.draft-quote',$order)),guideUrl=@json($shipment ? route('admin.shipments.guide',$shipment) : null);
    const message=(text,type='danger')=>{messageBox.className=`alert alert-${type} mt-3 mb-0`;messageBox.textContent=text};
    const escapeHtml=value=>{const node=document.createElement('div');node.textContent=value??'';return node.innerHTML};
    document.querySelector('#lookup-postal-code')?.addEventListener('click',async()=>{const cp=document.querySelector('#shipping-postal-code');if(!/^\d{5}$/.test(cp.value))return message('Escribe un código postal de 5 dígitos.');message('Consultando dirección…','info');try{const response=await fetch(`{{ url('/admin/shipments/postal-code') }}/${cp.value}`,{headers:{Accept:'application/json'}}),payload=await response.json();if(!response.ok)throw new Error(payload.message);const places=payload.places||[];if(!places.length)throw new Error('No encontramos colonias para ese código postal.');document.querySelector('#shipping-state').value=places[0].state;document.querySelector('#shipping-city').value=places[0].city;document.querySelector('#shipping-neighborhood').innerHTML=places.map(place=>`<option>${place.neighborhood}</option>`).join('');message(`${places.length} colonia(s) encontradas.`,'success')}catch(error){message(error.message)}});
    quoteButton.addEventListener('click',async()=>{quoteButton.disabled=true;rates.innerHTML='';message(isExisting?'Consultando tarifas con los datos guardados…':'Consultando tarifas de Skydropx…','info');try{const options=isExisting?{method:'POST',headers:{Accept:'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content}}:{method:'POST',body:new FormData(form),headers:{Accept:'application/json'}},response=await fetch(quoteUrl,options),payload=await response.json();if(!response.ok)throw new Error(payload.message||Object.values(payload.errors||{}).flat()[0]||'No se pudo cotizar.');if(!payload.rates?.length)throw new Error('Skydropx no devolvió tarifas disponibles.');rates.innerHTML='<h3 class="h5 fw-bold">Selecciona una tarifa</h3>'+payload.rates.map(rate=>`<button type="button" class="shipping-rate w-100" data-inline-rate='${JSON.stringify(rate).replaceAll("'","&#39;")}'><span><strong>${rate.carrier} · ${rate.service}</strong><small>${rate.days?rate.days+' días estimados':'Tiempo por confirmar'}</small></span><b>$${Number(rate.price).toFixed(2)}</b></button>`).join('');message('Tarifas listas. Selecciona una para vincular la guía.','success')}catch(error){message(error.message)}finally{quoteButton.disabled=false}});
    rates.addEventListener('click',async event=>{const button=event.target.closest('[data-inline-rate]');if(!button)return;const rate=JSON.parse(button.dataset.inlineRate);if(!isExisting){form.querySelector('[data-rate-id]').value=rate.id;form.querySelector('[data-rate-carrier]').value=rate.carrier;form.querySelector('[data-rate-service]').value=rate.service;form.querySelector('[data-rate-price]').value=rate.price;rates.querySelectorAll('.shipping-rate').forEach(item=>item.classList.toggle('is-selected',item===button));message('Tarifa seleccionada. Presiona “Crear seguimiento” para generar y vincular la guía.','success');return}const confirmed=await window.Swal.fire({title:'¿Generar esta guía?',text:`${rate.carrier} · ${rate.service} · $${Number(rate.price).toFixed(2)}`,icon:'question',showCancelButton:true,confirmButtonText:'Generar y vincular',cancelButtonText:'Cancelar'});if(!confirmed.isConfirmed)return;try{const response=await fetch(guideUrl,{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content},body:JSON.stringify({rate_id:rate.id,carrier:rate.carrier,service:rate.service,price:rate.price})}),payload=await response.json();if(!response.ok)throw new Error(payload.message);await window.Swal.fire({title:'Guía vinculada',text:payload.message,icon:'success',confirmButtonText:'Listo'});window.location.reload()}catch(error){window.Swal.fire({title:'No se pudo generar',text:error.message,icon:'error',confirmButtonText:'Entendido'})}});
    let availableGuides=[];const renderGuides=()=>{const term=(guideSearch?.value||'').trim().toLowerCase(),visible=availableGuides.filter(guide=>[guide.carrier,guide.service,guide.recipient,guide.tracking_number,guide.assigned_order].some(value=>String(value||'').toLowerCase().includes(term)));if(!visible.length){guideList.innerHTML='<div class="alert alert-info mb-0"><i class="bi bi-info-circle me-2"></i>No hay guías que coincidan con la búsqueda.</div>';return}guideList.innerHTML=visible.map(guide=>{const assignment=guide.assigned?`<span class="guide-assigned-badge"><i class="bi bi-check-circle-fill"></i>Guía asignada · ${escapeHtml(guide.assigned_order||'Otro pedido')}</span>`:'',action=guide.assigned?'<button class="btn btn-outline-success" type="button" disabled><i class="bi bi-lock-fill me-1"></i>Asignada</button>':`<button class="btn btn-primary" type="button" data-assign-guide="${encodeURIComponent(guide.id)}" data-guide-label="${encodeURIComponent((guide.tracking_number||guide.id)+' · '+guide.carrier)}"><i class="bi bi-link-45deg me-1"></i>Asignar</button>`;return `<article class="guide-assignment-item ${guide.assigned?'is-assigned':''}"><i class="bi bi-${guide.assigned?'check-circle-fill':'box-seam-fill'}"></i><div><strong>${escapeHtml(guide.carrier||'Paquetería')}${guide.service?' · '+escapeHtml(guide.service):''}</strong><span>${escapeHtml(guide.recipient||'Destinatario no disponible')}</span><small>${escapeHtml(guide.tracking_number||'Sin número de rastreo')} · ${escapeHtml((guide.status||'creada').replaceAll('_',' '))}</small>${assignment}</div>${action}</article>`}).join('')};
    assignButton?.addEventListener('click',async()=>{guideSearch.value='';guideList.innerHTML='<div class="text-center py-5 text-secondary"><span class="spinner-border spinner-border-sm me-2"></span>Consultando guías de Skydropx…</div>';try{const response=await fetch(@json(route('admin.shipments.available-guides',$order)),{headers:{Accept:'application/json'},cache:'no-store'}),payload=await response.json();if(!response.ok)throw new Error(payload.message);availableGuides=payload.guides||[];renderGuides()}catch(error){guideList.innerHTML=`<div class="alert alert-danger mb-0">${escapeHtml(error.message)}</div>`}});guideSearch?.addEventListener('input',renderGuides);
    guideList?.addEventListener('click',async event=>{const button=event.target.closest('[data-assign-guide]');if(!button)return;const confirmation=await window.Swal.fire({title:'¿Asignar esta guía?',text:decodeURIComponent(button.dataset.guideLabel),icon:'question',showCancelButton:true,confirmButtonText:'Sí, vincular',cancelButtonText:'Cancelar'});if(!confirmation.isConfirmed)return;button.disabled=true;try{const response=await fetch(@json(route('admin.shipments.assign-guide',$order)),{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content},body:JSON.stringify({guide_id:decodeURIComponent(button.dataset.assignGuide)})}),payload=await response.json();if(!response.ok)throw new Error(payload.message);document.querySelector('#assignGuideModal [data-bs-dismiss="modal"]')?.click();await window.Swal.fire({title:'Guía asignada',text:payload.message,icon:'success',confirmButtonText:'Listo'});window.location.reload()}catch(error){button.disabled=false;window.Swal.fire({title:'No se pudo asignar',text:error.message,icon:'error',confirmButtonText:'Entendido'})}});
});
</script>
@endif
